### ISSUE TITLE
Desabilitar lançamento de notas por aluno e manter apenas menu da nova interface de lançamento de notas

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#100]
MENU:
i-Educar - Escola > Movimentação > Lançamento por Turma
i-Educar - Escola > Movimentação > Lançamento por Aluno

PROBLEMA:
A funcionalidade disponível no menu Lançamento por Aluno é a primeira versão que existiu para o lançamento de notas e faltas e a existente no menu Lançamento por Turma é a versão criada pela Portabilis, que tornou o processo muito mais dinâmico. Não faz mais sentido mantermos a versão antiga, possibilitando também assim melhorarmos ainda mais a funcionalidade de lançamento por turma.

SOLUÇÃO:
- [x] Remover o menu Lançamento por Aluno e manter apenas o Lançamento por Turma, mantendo apenas o menu Movimentação > Faltas/notas que, inclusive, também permite o lançamento de notas e faltas somente de um aluno, bastando especificar isto no momento da seleção para lançamento.
- [x] Criar uma mensagem aos usuários ao se conectaram ao módulo i-Educar - Escola, para exibir o seguinte, explicando a mudança: ````Olá! Alteramos o menu do lançamento de notas, agora, acesse apenas <strong>Movimentação > Faltas/Notas</strong> e pronto! :)````

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
