### ISSUE TITLE
Criar opção para visualizar a informação da enturmação anterior do aluno

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#101]
MENU:
i-Educar - Escola > Cadastro > Aluno > Alunos - lista das matrículas

PROBLEMA:
Atualmente na listagem das matrículas, temos apenas o campo da Turma que apresenta a Turma atual, mas não é possível visualizar a turma que o aluno estava enturmado anteriormente.

SOLUÇÃO:
 - [ ] Criar uma opção ou campo na lista de matrículas do aluno para que seja possível visualizar a última enturmação realizada para o aluno, independentemente se ele esteja ou não enturmado.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá,

Essa feature foi implementada juntamente com o commit: https://github.com/portabilis/ieducar/commit/c745fcdd2cb40853931b5ba5eb537cfb28862622#diff-21c95012edd20f06212e68a86aab715aR537
