### ISSUE TITLE
Aprimorar mensagem de validação em enturmações quando não existem alunos para serem enturmados

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#102]
MENU:
i-Educar - Escola > Movimentação > Enturmação

PROBLEMA:
A mensagem de aviso que é exibida nesta funcionalidade, informando "Não existem alunos não enturmados na série" não condiz com a realidade. Atualmente, são listados todos os alunos enturmados em um campo textfield bloqueado e os alunos não enturmados, com um opção checkbox para enturmá-lo. Caso não hajam alunos não enturmados, é apresentada a seguinte mensagem :

"Todos os alunos matriculados na série já se encontram enturmados."

Porém, quando não existem matriculados na série a mesma mensagem é apresentada.

SOLUÇÃO:
- [x] Efetuar alteração da mensagem para o usuário nesta funcionalidade, facilitando a compreensão da situação atual. Sugestão de mensagem: "Não há alunos enturmados."

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
