### ISSUE TITLE
Aprimorar filtragem pelo código do aluno e código do INEP permitindo valores maiores

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#103]
MENU:
i-Educar - Escola > Cadastros > Aluno > Alunos

PROBLEMA:
Na listagem de alunos, ao pesquisar alunos pelo código do aluno ou código INEP e informar um valor muito grande (maior que 10 dígitos), está ocorrendo uma mensagem de erro inesperado.

Exemplo: o formato do código INEP é de 12 dígitos. Se pesquisar por '189874873999' que é um código INEP válido, é possível simular o erro.

SOLUÇÃO:
- [x] Adaptar a busca para que valores muito grande de código do aluno ou código INEP, possam ser filtrados sem que ocorram problemas.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
