### ISSUE TITLE
Criar data efetiva do processo da matrícula, transferência, reclassificação, abandono e outros

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#104]
MENU:
i-Educar - Escola > Cadastros > Aluno > Alunos

PROBLEMA:
Para os processos da matrícula de um aluno, como nova matrícula, transferência, reclassificação, abandono, rematrícula automática e outros, não existem datas efetivas informadas pelo usuário, somente aquelas geradas pelo sistema. Muitas vezes, o processo no sistema é feito posteriormente a data efetiva do processo, logo, é necessário que se possa informar a data efetiva do processo.

SOLUÇÃO:
- [ ] Criar um campo onde o usuário possa digitar a data efetiva livremente em que um processo foi executado, seja de admissão ou saída. Ex.: permitir na matrícula o usuário informar a Data da matrícula e permitir no Abandono ou Transferência externa, a data de saída.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
