### ISSUE TITLE
Alterar processo de empréstimos de exemplares para considerar os dias da semana e feriados corretamente

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#105]
MENU:
i-Educar - Biblioteca > Cadastro > Dados Biblioteca

PROBLEMA:
No processo de empréstimo de exemplares, quando a data de entrega cai em um final de semana, em um dia da semana que a biblioteca não abre ou em um feriado, a data de entrega dos exemplares não é adiada, gerando multa ao cliente da biblioteca.

SOLUÇÃO:
- [x] Alterar o processo de empréstimo de exemplares para que a data prevista de devolução considere os dias da semana e feriados cadastrados corretamente.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
