### ISSUE TITLE
Remover obrigatoriedade dos campos preço e data de aquisição no cadastro de exemplar

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#106]
MENU:
i-Educar - Biblioteca > Cadastro > Exemplares

PROBLEMA:
Atualmente os campos "Preço" e "Data de Aquisição" são obrigatórios para o cadastro de um exemplar e nem sempre a biblioteca possui tais informações.

SOLUÇÃO:
- [x] Remover a obrigatoriedade dos campos e alterar o label do campo "Data de Aquisição" para "Data de Entrada", pois em estudos com alguns clientes e usuários foi solicitada esta como nomenclatura ideal.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
