### ISSUE TITLE
Alterar o cadastro de funcionários para que as opções super usuário, banido e matrícula permanente sejam exibidas corretamente

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#107]
MENU:
DRH > Cadastro de Funcionários

PROBLEMA:
Ao criar um novo usuário e ceder as permissões, notou-se que o checkbox referente ao "Super usuário", o checkbox de "Banido" e o de 'Matrícula permanente" não permanecem marcados após terem sido salvos.

SOLUÇÃO:
- [ ] Alterar para que após marcar estas opções na lista de permissões do usuário estas sejam salvadas corretamente no banco de dados e/ou exibidas corretamente no formulário, caso o problema seja apenas na interface.

OBSERVAÇÕES:
Não se aplica

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
