### ISSUE TITLE
Adicionar validação para não permitir realizar empréstimos para exemplares reservados

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#108]
MENU:
i-Educar - Biblioteca > Movimentação > Empréstimo

PROBLEMA:
Mesmo quando um exemplar já está reservado, o sistema permite o empréstimo do mesmo.

SOLUÇÃO:
- [x] Alterar validação para que quando o exemplar estiver reservado, o sistema não permita o empréstimo e caso o usuário tente efetuar o empréstimo, exiba uma mensagem intuitiva com o motivo.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
