### ISSUE TITLE
Adicionar validação para impedir que seja cadastrado mais que um cliente para a mesma pessoa

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#109]
MENU:
i-Educar - Biblioteca > Movimentação > Clientes

PROBLEMA:
Atualmente o sistema permite cadastrar mais de um cliente para a mesma pessoa, usando tipos de clientes diferentes. Outra questão é que ao tentar cadastrar dois clientes para mesma pessoa, com o mesmo tipo de cliente ocorre um erro no banco, de violação de chave única.

SOLUÇÃO:
- [ ] Adicionar validação para impedir que seja cadastrado mais que um cliente para a mesma pessoa.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
