### ISSUE TITLE
Alterar processo de reclassificação de alunos para concluir o processo sem que ocorram falhas

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#110]
MENU:
Cadastros > Aluno > Alunos - Selecionar matrícula e clicar em Reclassificar

PROBLEMA:
Ao tentar realizar o processo de reclassificação de um aluno na gestão da matrícula, o processo simplesmente não finaliza, exibindo uma tela em branco.

SOLUÇÃO:
- [x] Corrigir para que seja possível efetuar a reclassificação de alunos.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá,

esse problema não ocorre mais.
