### ISSUE TITLE
Modal de busca de endereço em pessoas físicas não está exibindo paginação dos registros

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#111]
MENU:
Pessoa F/J > Pessoa Física

PROBLEMA:
Ao cadastrar uma pessoa, é necessário informar o endereço da mesma. Ocorre que ao clicar sobre a lupa ao lado do campo CEP e pesquisar por um bairro, as ruas serão listadas, porém, os botões de navegação permanecem desabilitados, mesmo que existam mais endereços a serem exibidos.

SOLUÇÃO:
- [ ] Habilitar os botões de navegação na lupa do endereço em Pessoas físicas para que sejam exibidos todos os endereços na modal de busca.

OBSERVAÇÕES:
Não se aplica

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
