### ISSUE TITLE
Alterar cadastro de tipos de usuários para salvar corretamente opções de permissões editadas

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#112]
MENU:
i-Educar - Escola > Administrativo > Tipo de Usuário

PROBLEMA:
Ao editar um tipo de usuário, conceder as permissões para ele e salvar, vários dos campos checkbox não permanecem salvos e ao editar novamente, eles estão desmarcados. Ex.: checkbox referentes às opções de excluir, do módulo Biblioteca.

SOLUÇÃO:
- [x] Alterar para que no cadastro de tipo de usuário as opções marcadas nos checkbox sejam todas salvas no banco de dados.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
