### ISSUE TITLE
Criar data efetiva do processo de enturmação em todas as funcionalidades de enturmação

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#113]
MENU:
i-Educar - Escola > Cadastro > Alunos > Matrícula > Nova matrícula (Enturmação direta)
i-Educar - Escola > Cadastro > Alunos > Matrícula > Enturmar
i-Educar - Escola > Movimentações > Enturmação

PROBLEMA:
Atualmente não é possível informar uma data efetiva (processo) de uma enturmação, gravando sempre como data da enturmação a data 

SOLUÇÃO: 
- [x] Adicionar campos para informar a data da enturmação em todas as funcionalidades onde existir o processo de enturmação.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
