### ISSUE TITLE
Criar controle de fechamento de turmas e ordenação de lista de alunos para atender a integração com sistema PRODESP/GDAE do Estado de SP

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#114]
MENU:
i-Educar - Escola > Cadastros > Turma > Cadastrar

PROBLEMA:
Em função de uma necessidade de clientes e usuários do Estado de São Paulo, visando o controle e integração dos alunos gerenciados no sistema PRODESP/GDAE, faz-se necessário controlar ordenações de alunos nas turmas de forma diferenciada, de acordo com uma data base (de fechamento da turma). 

Atualmente, os alunos matriculados durante o ano letivo são exibidos em ordem alfabética nas listagens das funcionalidades e relatórios, o que dificulta o controle da escola, pois entram em conflito com a listagem do PRODESP/GDAE.

SOLUÇÃO:
- [x] Adicionar um controle de data base para fechamento de turmas, onde as admissões (enturmações) efetuadas até esta data base, continuarão funcionando da forma atual, porém, enturmações efetuadas após esta data, deve apresentar a lista dos alunos por ordem de chegada/admissão na turma, 

OBSERVAÇÕES:
Alteração exclusiva para clientes do Estado de São Paulo, por isso, opção deve ser opcional no sistema.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.

**Comment by JDias** [comment]
Compartilhando 

https://github.com/tmarquesini/sed-data
