### ISSUE TITLE
Alterar ordenação da listagem de alunos em todo o sistema para atender a integração com sistema PRODESP/GDAE do Estado de SP

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#115]
MENU:
i-Educar - Escola > Cadastros > Turma > Cadastrar
i-Educar - Escola > Movimentação > Faltas/Notas > Lançamento por Turma
i-Educar - Escola > Movimentação > Processos > Histórico Escolar

SOLUÇÃO:
- [x] A tarefa #114 cria a opção para informar uma data de fechamento de turma e esta tarefa deverá prever as alterações em todo o sistema onde apresentam listagem de alunos, para não exibir mais em ordem alfabética e sim de acordo com a data de fechamento da turma e por ordem de enturmação/admissão, após a data de fechamento. 

OBSERVAÇÕES:
Ref. a alterações da tarefa https://github.com/portabilis/ieducar/issues/114

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
