### ISSUE TITLE
Criar função no banco de dados para calcular a próxima data prevista para entrega de um exemplar

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#116]
MENU:
i-Educar - Biblioteca

SOLUÇÃO:
- [ ] Devido a necessidade de se conhecer a data em que um exemplar deve ser devolvido a biblioteca, faz-se necessário criar uma função de banco de dados para verificar a próxima data prevista para entrega, considerando dias da semana e feriados da biblioteca.

OBSERVAÇÕES:
Este recurso pode ser utilizado em conjunto com a refatoração feita no processo de empréstimos na tarefa https://github.com/portabilis/ieducar/issues/105, tanto para criar novas funcionalidades que utilizem estas informações quanto para o desenvolvimento de relatórios.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
