### ISSUE TITLE
Corrigir erro de SQL inválido exibido ao usuário ao finalizar o cadastro de um exemplar

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#117]
MENU:
i-Educar - Biblioteca > Cadastro > Exemplares

PROBLEMA:
Ao cadastrar um exemplar, em alguns casos, o sistema está apresentando uma mensagem de erro como esta, muito embora, cadastra o exemplar normalmente.

````Erro ao executar uma ação no banco de dados: SQL invalido: INSERT INTO pmieducar.exemplar ( ref_cod_fonte, ref_cod_acervo, ref_cod_situacao, ref_usuario_cad, permite_emprestimo, preco, tombo, data_cadastro, ativo, data_aquisicao ) VALUES( '1', '1', '1', '1', '2', '0', '3', NOW(), '1', '--2013-10-28' )````

SOLUÇÃO:
- [ ] Corrigir o problema para que seja possível cadastrar exemplares normalmente, sem quem ocorram mensagens de erro.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
