### ISSUE TITLE
Adicionar validação para permitir cadastrar, editar e buscar autores cujo nome contenham um apóstrofo

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#118]
MENU:
i-Educar - Biblioteca > Cadastro > Autores

PROBLEMA:
Ao cadastrar, editar ou buscar um autor, cujo nome possua um apóstrofo, é emitida uma mensagem de erro: 
Erro php
pg_query(): Query failed: ERROR: syntax error at or near "er" LINE 1: ...tivo, ref_cod_biblioteca ) VALUES( '1', 'Jack Rip'er', '', N... ^

SOLUÇÃO:
- [x] Adicionar validações para permitir o cadastro, edição e busca normalmente de nomes de autores como "Sant'ana" e "Rip'er".

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
