### ISSUE TITLE
Corrigir cadastro de CEPs para que seja possível excluir adequadamente os registros

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#119]
MENU:
Endereçamento > CEP

PROBLEMA:
Ao tentar excluir um CEP cadastrado no menu Endereçamento >> CEP, o mesmo não é excluído. Percebe-se que ao tentar editar o mesmo CEP, ocorre um bug onde o primeiro CEP cadastrado não é mais vinculado e ao vincular novamente e gravar a operação é criado outro CEP, duplicando-os.

SOLUÇÃO:
- [ ] Corrigir o cadastro de CEPs para que seja possível excluir adequadamente os registros de CEPs já cadastrados.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá, @giustin!

Foi utilizado uma solução alternativa, para CEPs já cadastrados foi removido o botão de exclusão, pois o mesmo pode ter vínculos com pessoas.
Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
