### ISSUE TITLE
Remover campo "Biblioteca possui tombo automático" do cadastro de dados da biblioteca

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#120]
MENU:
i-Educar - Biblioteca > Cadastro > Dados Biblioteca

PROBLEMA
Atualmente temos no cadastro o campo "Biblioteca possui tombo automático", mas o cadastro de exemplares não depende mais de tal configuração, pois o tombo é considerado como manual quando informado pelo usuário, ou automático quando não informado nenhum valor (onde é buscado o maior tombo + 1).

SOLUÇÃO:
- [x] Remover o campo "Biblioteca possui tombo automático" da interface pois não possui funcionalidade prática.

OBSERVAÇÕES:
https://github.com/portabilis/i-educar/issues/218

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
