### ISSUE TITLE
Criar relação do assunto com obra no mód. biblioteca para facilitar a pesquisa de obras por assunto

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#122]
MENU:
i-Educar - Biblioteca > Cadastro > Assunto
i-Educar - Biblioteca > Cadastro > Obras

PROBLEMA:
Atualmente, o cadastro de Assuntos atualmente não possui funcionalidade prática no módulo. Além disso, faz sentido cadastrar e pesquisar exemplares de obras por assunto, mas hoje não existe relação entre assunto e obras.

SOLUÇÃO:
- [x] Criar relação do Assunto com a Obra para ajudar na pesquisa por um determinado tipo de obra literária por assunto.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
