### ISSUE TITLE
Criar parâmetro ou opção que permita personalizar a nomenclatura do campo nota do exame

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#123]
MENU:
i-Educar - Escola > Movimentação > Faltas/Notas

PROBLEMA:
Durante o trabalho com alguns municípios, essencialmente do Estado de SP, observou-se diferentes formas de nomenclaturas para a Nota de exame.

SOLUÇÃO:
- [ ] Alterar o sistema para que quando exibir no lançamento de notas e faltas após lançamento da última etapa o campo para a nota do exame, que a nomenclatura possa ser personalizada de acordo com a realidade de cada município.

Ex.: Com alteração, deve ser possível personalizar a nomenclatura de "Nota exame" para "Nota do conselho."

OBSERVAÇÃO:
Este recurso, se desenvolvido como variável de ambiente, poderá ser utilizado tanto na aplicação quando relatórios.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
