### ISSUE TITLE
Adaptar o sistema para atender ao AEE e Programa Mais Educação com cursos simultâneos em contraturno

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#124]
MENU:
i-Educar - Escola > Cadastro > Aluno > Alunos

PROBLEMA:
Atualmente, o sistema permite apenas uma matrícula vigente em um curso/série/turma. Porém, com a necessidade de atendimento ao AEE (Atendimento Educacional Especializado) e Programa Mais Educação, onde o aluno pode frequentar o ensino regular e também outra atividade/grade em um contraturno, faz-se necessário adaptar para o atendimento desta legislação.

SOLUÇÃO:
- [x] Adaptar o sistema para permitir efetuar matrículas simultâneas em cursos diferentes, para atendimento ao AEE, Mais Educação e outras atividade que exijam controle simultâneos em grades/cursos diferentes.

OBSERVAÇÕES:
Avaliar possibilidade de manter o comportamento padrão do sistema como é atualmente e criar uma personalização para que possa ser customizado conforme a necessidade.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
