### ISSUE TITLE
Desabilitar função que faz rematrículas automáticas ao iniciar um novo ano letivo sem o consentimento do usuário

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#125]
MENU:
i-Educar - Escola > Cadastro > Escola > Cadastrar

PROBLEMA:
Atualmente, ao definir um ano letivo no sistema e em seguida iniciar este ano letivo, todas as matrículas do ano anterior são automaticamente rematriculadas no ano iniciado, o que é um comportamento que não faz sentido na prática, não tem transparência e gera retrabalho para os secretários de escolas, que precisam cancelar matrícula de alunos que o pai não necessariamente solicitou rematrícula naquela escola ou nem mesmo transferência para outra ainda. Além disso, existe o processo de Rematrícula automática, que faz justamente este processo, porém, por decisão e consentimento do usuário.

SOLUÇÃO:
- [x] Desabilitar o recurso que faz as rematrículas automaticamente ao iniciar um novo ano letivo.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá, @giustin!

Essa função já foi parametrizada nesse commit[1], vou apenas alterar o parâmetro para que por padrão essa função seja desativada.

1: https://github.com/portabilis/ieducar/commit/55baf87f7586d9cdbd5d4cf015fcfab460e6a80f

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.

**Comment by giustin** [comment]
Olá, @lucassch !

Favor aplicar a implementação que já desenvolvemos e validamos com clientes. Pelas experiências que observei nos municípios, em nenhum situação eles aprovaram um processo que executa sem seu consentimento, rematriculando alunos automaticamente ao abrir o ano letivo da escolas.

Veja neste caso, como tratar o pull request já aceito, informando para o desenvolvedor alterar para o parâmetro aplicar o reverso, se for realmente necessário esta rematrícula para alguma caso em específico.

[1] https://github.com/portabilis/ieducar/commit/55baf87f7586d9cdbd5d4cf015fcfab460e6a80f

**Comment by carolinesalib** [comment]
Olá, @giustin!

Parâmetro retirado e implementado versão da Portabilis [1].

Disponível no link [1], favor verificar se está tudo ok para que eu possa repassar as modificações para o GitLab na comunidade.

[1] https://github.com/portabilis/i-educar/issues/596
[2] http://comunidade.ieducar.com.br

**Comment by giustin** [comment]
Olá, @carolinesalib !

Desculpe a demora. Homologuei esta tarefa e já pode ser transferida para o ambiente da Comunidade e finalizar a tarefa lá [1]. Obrigado!

[1] https://softwarepublico.gov.br/gitlab/i-educar/i-educar/issues/8

**Comment by carolinesalib** [comment]
Olá, @giustin!

Esta tarefa já foi homologada na comunidade e os commits estão referenciados na issue [1] para qualquer dúvida.

[1] https://softwarepublico.gov.br/gitlab/i-educar/i-educar/issues/8

**Comment by kesllan** [comment]
Olá! Como ativar a rematricula automática na versão 2.6.8? ou esse recurso foi removido em definitivo do código?
