### ISSUE TITLE
Melhorar o processo de rematrícula automática para listar alunos rematriculados e exibir mensagens intuitivas ao usuário

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#126]
MENU:
i-Educar - Escola > Movimentação > Rematrícula Automática

PROBLEMA:
Atualmente, o processo de rematrícula automática é confuso pois quando o usuário executa o processo, não tem certeza se funcionou ou não, já que nenhuma informação do alunos rematriculados é exibida, muito menos mensagem de confirmação do processo.

SOLUÇÃO: 
- [x] Alterar para que quando executado o processo de rematrícula, sejam listados os alunos que irão ser rematriculados no ano letivo seguinte;
- [x] Alterar para que mensagens de validação e informação ao usuário sobre o que está acontecendo, seja exibidas na página, facilitando a interação;
- [x] Alterar para que no campo que seleciona a turma, seja exibido o ano letivo da turma, para não confundir com as turmas do ano letivo vigente (seguinte).

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
