### ISSUE TITLE
Aprimorar processo de enturmação em lote para permitir a desenturmação em lote na mesma funcionalidade

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#127]
MENU:
i-Educar - Escola > Movimentação > Enturmação

PROBLEMA:
Ao acessar uma turma nesta funcionalidade que contenha alunos enturmados, a lista destes alunos aparece desabilitada, não permitindo nenhuma operação com estes alunos. Todavia, se existirem alunos  matriculados na série desta turma, mas não enturmados, é possível gerenciar marcação nos checkbox daqueles que serão enturmados. Mesmo assim, faria sentido ter uma opção para reverter o processo, ou seja, selecionar alunos para desenturmar também.

SOLUÇÃO:
- [x] Melhorar a funcionalidade de enturmação em lote permitindo que sejam enturmados vários alunos de uma vez como é hoje, mas também permitir desenturmar os alunos da turma, vários de uma vez, utilizando marcações na listagem de alunos apresentada.
- [x] Avaliar outros tratamentos necessários como a melhoria na exibição de labels e validações da funcionalidade.

Como é atualmente:
![image](https://cloud.githubusercontent.com/assets/1082624/6612268/e8209092-c857-11e4-982f-b37039658939.png)
Proposta de mudanças na listagem:
![image](https://cloud.githubusercontent.com/assets/1082624/6612275/06b80396-c858-11e4-82de-354bb9a8cc78.png)

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
