### ISSUE TITLE
Criar migração para excluir do banco de dados deficiência chamada "Nenhuma"

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#128]
MENU:
i-Educar - Escola > Cadastros > Deficiências
i-Educar - Escola > Cadastros > Aluno > Alunos > Editar

PROBLEMA:
Atualmente, uma deficiência chamada "Nenhuma" vem pré-cadastrada no banco de dados para utilização no cadastro de alunos. Isto não faz sentido, pois se o aluno não possui nenhuma deficiência, não precisa selecionar uma deficiência nomeada como "Nenhuma". Além disso, não faz sentido selecionar esta deficiência e outras junto.

SOLUÇÃO: 
- [x] Criar uma migração que remova este tipo de deficiência do banco de dados e quando o aluno não possuir nenhuma deficiência, basta não informar nenhuma.

INTERESSADOS:
Dom Eliseu - PA e todos os clientes.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
