### ISSUE TITLE
Aprimorar processo de exclusão de um tipo de deficiência para evitar de falhas de integridade

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#129]
MENU:
i-Educar - Escola > Cadastros > Deficiências

PROBLEMA:
Ao tentar excluir um tipo de deficiência cadastrada que esteja vinculada a alunos ocorre um erro de SQL.

SOLUÇÃO:
- [x] Validar o processo de exclusão de uma deficiência que tenha relação com um aluno, para que não ocorram erros no sistema e exiba mensagem ao usuário indicando a situação atual.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
