### ISSUE TITLE
Criar recurso para armazenar a nota necessária no exame para fins de apresentação em outros locais como relatórios

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#130]
MENU:
i-Educar - Escola > Movimentação > Faltas/notas

PROBLEMA:
Atualmente já temos o recurso na interface de lançamento de notas que exibe a nota necessária que um aluno necessita alcançar para ser promovido no exame, porém, esta informação é importante para apresentarmos também em relatórios e como esta informação é processada em tempo de execução e não armazenada no banco de dados, inviabiliza por exemplo elaborar um relatório com estas informações.

SOLUÇÃO:
- [ ] Criar um recurso que permita armazenar a nota necessária no exame para cada aluno enquadrado nesta situação, permitindo a utilização desta informação para outras finalidades como o desenvolvimento de relatórios.

OBSERVAÇÕES:
A partir desta tarefa será possível criar visões em outras funcionalidades do sistema ou relatório com a informação da nota necessária no exame.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
