### ISSUE TITLE
Erro ao cadastrar carga horária maior que 24 horas

### ISSUE THREAD

**Issue by gabrielms** [portabilis/ieducar#134]
MENU:
Servidores > Cadastrar > Alocar servidor

PROBLEMA:
Ao tentar alocar uma servidor com uma carga horária maior que 24 horas o sistema acusa um erro inesperado, print:
![image](https://cloud.githubusercontent.com/assets/1145088/7280360/804afc02-e8f8-11e4-964f-4b9241054156.png)

SOLUÇÃO:
Avaliar viabilidade de mudar o formato do campo, visto que o campo atual é do tipo time e só aceita até 24 horas.

**Comment by carolinesalib** [comment]
Problema já resolvido no commit: 1632a67dd2f7ffbb5387575e1168932b70cd8286
