### ISSUE TITLE
Tratar mensagem de SQL inválido ao criar um usuário que já possua permissões individuais concedidas

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#142]
MENU:
i-Educar - Escola > Administrativo > Usuários
DRH > Cadastro de Funcionários

PROBLEMA:
Ao criar um usuário novo concedendo suas permissões diretamente em DRH > Cadastro de Funcionários e então vincular ele a uma escola em Administrativo > Usuários é apresentado as mensagens:

'Notice: Trying to get property of non-object in /home/ricardo/projects/ieducar/portabilis/ieducar/intranet/clsConfigItajai.inc.php on line 88 Notice: Trying to get property of non-object in /home/ricardo/projects/ieducar/portabilis/ieducar/intranet/clsConfigItajai.inc.php on line 88'

Detalhes:

Erro app
Erro ao executar uma ação no banco de dados: SQL invalido: INSERT INTO menu_funcionario (ref_ref_cod_pessoa_fj, ref_cod_menu_submenu , cadastra, exclui) VALUES ('152', '43' , '1', '1')

Erro php
pg_query(): Query failed: ERROR: duplicate key violates unique constraint "menu_funcionario_pk"
Arquivo
(linha: 434) /home/ricardo/projects/ieducar/portabilis/ieducar/intranet/include/clsBancoPgSql.inc.php

SOLUÇÃO: 
- [ ] Criar mensagem amigável para o usuário, avisando que foram concedidas permissões em DRH antes de vincular o usuário ou outra alternativa para evitar este problema.

OBSERVAÇÕES:
Não se aplica.

**Comment by carolinesalib** [comment]
Na issue #85 já havia sido corrigido o erro ao criar um novo usuário. Agora foi corrigido para que o erro não aconteça ao editar o usuário.
