### ISSUE TITLE
Exibir os módulos do ano letivo anterior ao cadastrar um novo ano letivo para a escola

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#143]
MENU:
i-Educar - Escola > Cadastros > Escola > Cadastrar > Selecionar uma escola > Definir Ano Letivo
i-Educar - Escola - Cadastros > Escola > Cadastrar > Selecionar uma escola > Editar ano letivo

PROBLEMA:
A tela de cadastro de um novo ano letivo é um pouco confusa e os usuários muitas vezes não sabem como montar os módulos (etapas) de cada ano letivo.

SOLUÇÃO: 
- [x] Alterar a tela de cadastro de ano letivos para exibir os módulos do ano letivo anterior facilitando a inserção das etapas do ano vigente.

OBSERVAÇÕES:
Não se aplica.

**Comment by carolinesalib** [comment]
Foi alterado para que apareça os módulos do ano letivo anterior no cadastro de ano letivo, conforme imagem abaixo:
 
![image](https://cloud.githubusercontent.com/assets/5773360/8931228/fe022a68-350a-11e5-934b-f93a9d84c512.png)

Esta alteração estará disponível no próximo deploy previsto para 31/07/2015 e poderá ser conferida no ambiente de demonstração da Comunidade no endereço https://portal.softwarepublico.gov.br/social/i-educar
