### ISSUE TITLE
Corrigir problema de alteração automática de Tipo menu (Preferências) ao editar os dados do usuário

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#144]
MENU:
Principal > Preferências > Tipo menu

PROBLEMA:
Após criar um usuário (funcionário) e as informações de preferência do menu forem definidas, ao editar qualquer informação deste usuário, o Tipo menu volta para o tipo "Menu padrão", se estivesse definido o "Menu Suspenso".

SOLUÇÃO: 
- [ ] Alterar para que quando o Tipo menu for designado pelo usuário, não se modifique ao fazer qualquer alteração no cadastro, por exemplo, ao alterar a senha do usuário.

OBSERVAÇÕES:
Não se aplica.

**Comment by carolinesalib** [comment]
Olá!

Problema corrigido, o mesmo acontecia quando ao editar alguma informação no cadastro de algum usuário com menu do tipo "padrão", o mesmo era alterado involuntariamente para o tipo "suspenso".

Esta alteração estará disponível no próximo deploy previsto para 31/07/2015 e poderá ser conferida no ambiente de demonstração da Comunidade no endereço https://portal.softwarepublico.gov.br/social/i-educar
