### ISSUE TITLE
Aprimorar cadastro, edição e visualização dos módulos da turma e dias da semana 

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#145]
MENU:
i-Educar - Escola > Cadastros > Turmas > Cadastrar

PROBLEMA:
Ao criar uma turma nova e adicionar módulos na turma - situação que ocorre quando o campo Padrão Ano Escolar não estiver marcado no cadastro do Curso - ao gravar os módulos a informação é apresentada, mas ao sair e voltar ao cadastro da turma em módulo Detalhe, a informação não é apresentada. Problema também ocorre ao editar uma turma.

Já foi possível simular também o problema para a seção Dias da semana, e a falha às vezes ocorre no navegador Chrome ou Firefox.

Imagem ilustrativa do cadastro de módulos e dias da semana:
![image](https://cloud.githubusercontent.com/assets/1082624/8876617/2c206d0e-31f7-11e5-843d-1d03c44b2004.png)

SOLUÇÃO: 
- [x] Corrigir para que ao cadastrar, editar ou visualizar uma turma, os módulos da turma sejam cadastrados, visualizados e editados sem falhas;
- [x] Aplicar as mesmas correções para a seção Dias da semana e validar esta alteração para diferentes navegadores (Chrome, Firefox, etc).

OBSERVAÇÕES:
Não se aplica.

**Comment by carolinesalib** [comment]
Olá!

* Foi corrigido para que apareça todos os módulos cadastrados na edição da turma.
![image](https://cloud.githubusercontent.com/assets/5773360/8965649/4173f86e-3603-11e5-9f2d-2ba7bcf02cb6.png)
* Foi ajustado também para a tela rolar de volta para os módulos após adicionar ou excluir um módulo, o mesmo serviu para os dias da semana. 
* Foi corrigido alguns bugs para que funcione corretamente a edição e visualização do cadastro de turma nos navegadores Google Chrome e Firefox.

Esta alteração estará disponível no próximo deploy previsto para 31/07/2015 e poderá ser conferida no ambiente de demonstração da Comunidade no endereço https://portal.softwarepublico.gov.br/social/i-educar
