### ISSUE TITLE
Adicionar títulos de localização (breadcrumb) em todos os cadastros e processos do sistema melhorando a usabilidade

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#146]
MENU:
Todos os módulos e funcionalidades

PROBLEMA:
Atualmente ao acessar um determinado cadastro ou relatório do sistema não é indicada a localização atual do usuário no sistema, nem ao menos informa o título do cadastro. Isto chama-se Navegação estruturada ou como é conhecido o termo em inglês - breadcrumb [1].

Anteriormente, alunos da UnB em um projeto acadêmico em parceria com a Portabilis, implementaram por meio da tarefa #15 uma parte deste processo, aplicando em alguns cadastros. Todavia, faz-se necessário a aplicação em todo o sistema e a inclusão de uma nova proposta de apresentação de design, bem como uma padronização dos títulos (Cadastro, Edição, Detalhe, Listagem). 

Abaixo, é apresenta uma imagem da tela de aluno do que já foi implementado:
![image](https://cloud.githubusercontent.com/assets/1082624/8877023/9783406a-31f9-11e5-888c-8f8689992027.png)

SOLUÇÃO:
Analisar uma forma de exibir um título de cada cadastro e relatório, dos módulos Escola e Biblioteca. A proposta é que seja utilizado o próprio título dado ao cadastro ou relatório, nas permissões do usuário em DRH >> Funcionários, as quais caso não estejam descritas de forma objetiva ao cadastro ou relatório, poderão ser reescritass.

O título do cadastro ou relatório deve ser exibido imediamente abaixo do menu suspenso, tanto em modo Listagem, Detalhe, quanto Edição de cada cadastro, exempos:

i-Educar - Escola > Listagem de alunos
i-Educar - Escola > Detalhe do aluno
i-Educar - Escola > Cadastro do aluno
(...)

OBSERVAÇÕES:
[1] https://pt.wikipedia.org/wiki/Navega%C3%A7%C3%A3o_estrutural
[2] https://github.com/portabilis/ieducar/issues/15

**Comment by carolinesalib** [comment]
Olá!

* Foi adicionado títulos em todo o sistema i-Educar;
* Foi alterado o layout dos títulos do i-Educar;
* Foi adicionando links para melhor localização dentro do i-Educar, através dos títulos adicionados em todo o sistema.
![image](https://cloud.githubusercontent.com/assets/5773360/9429594/09761660-49ac-11e5-8c24-62898afa48ee.png)

Esta alteração estará disponível no próximo deploy previsto para 31/08/2015 e poderá ser conferida no ambiente de demonstração da Comunidade no endereço https://portal.softwarepublico.gov.br/social/i-educar

**Comment by carolinesalib** [comment]
Reaberto a issue para ajuste do problema citado no portal do SPB: https://softwarepublico.gov.br/gitlab/i-educar/i-educar/issues/4

**Comment by carolinesalib** [comment]
Olá!

Bug corrigido e já disponível no ambiente: http://comunidade.ieducar.com.br/
