### ISSUE TITLE
Criar campo Número da carteira do SUS no cadastro da pessoa e aluno na aba Ficha médica

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#147]
MENU:
Pessoas FJ > Pessoa Física
i-Educar - Escola > Cadastros > Alunos > Cadastrar > Ficha médica

PROBLEMA:
Atualmente não existe um campo para informar o número do cartão do SUS.

SOLUÇÃO:
- [x] Adicionar um campo tipo char tamanho 20 com o label "Número da Carteira do SUS" e exibir no cadastro da pessoa e Ficha médica do aluno, logo abaixo do campo Fator RH.

OBSERVAÇÕES:
Não se aplica

**Comment by carolinesalib** [comment]
Olá!

* Foi adicionado o campo "Número da carteira do SUS" no cadastro de pessoa física.

Esta alteração estará disponível no próximo deploy previsto para 31/08/2015 e poderá ser conferida no ambiente de demonstração da Comunidade no endereço https://portal.softwarepublico.gov.br/social/i-educar
