### ISSUE TITLE
Criar campo NIS/PIS/PASEP no cadastro de pessoas físicas (Educacenso/INEP)

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#148]
MENU:
Pessoas FJ > Pessoa Física

PROBLEMA:
Faz-se necessária a adaptação do sistema para atender ao layout de dados do Educacenso/INEP, visando a exportação de dados automatizada.

SOLUÇÃO:
- [x] Adicionar um campo char com o label "NIS (PIS/PASEP)" no cadastro de pessoas.

OBSERVAÇÕES:
Não se aplica

**Comment by carolinesalib** [comment]
Olá!

* Foi adicionado o campo "NIS (PIS/PASEP)" no cadastro de pessoa física.

![image](https://cloud.githubusercontent.com/assets/5773360/9482462/018fe29e-4b6b-11e5-9b52-296416c46e93.png)

Esta alteração estará disponível no próximo deploy previsto para 31/08/2015 e poderá ser conferida no ambiente de demonstração da Comunidade no endereço https://portal.softwarepublico.gov.br/social/i-educar

**Comment by lucasdavila** [comment]
Oi @carolinesalib, tudo bem?

Eu não encontrei a migração SQL que adicionou este campo ao banco de dados, eu acredito que você tenha esquecido de adicionar ao commit.

Você pode disponibiliza-la por favor?

**Comment by carolinesalib** [comment]
Oi @lucasdavila, tudo certo. 

Esse campo não existe na sua base de dados? To achando estranho, porque na verdade quando eu migrei essa tarefa o campo já existia. E até fui dar uma investigada, e o campo já existe na base antes mesmos de serem feitas as migrações a partir da 53..

De qualquer forma, segue o script para criação do campo:
> ALTER TABLE cadastro.fisica ADD COLUMN nis_pis_pasep numeric(11,0);

Abraço.

**Comment by lucasdavila** [comment]
@carolinesalib isto, o campo não existe na base de dados.

Realizei um search no código fonte e não encontrei nenhuma migração criando ele. Pode ser que a migração não adicionada em algum commit passado então.

Obrigado.
