### ISSUE TITLE
Corrigir erro gramatical no cadastro de ocorrências disciplinares dos alunos

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#149]
MENU:
i-Educar - Escola > Cadastros > Alunos > Cadastrar

PROBLEMA:
Atualmente existem problemas com a gramática do processo de Ocorrências disciplinares, que não tem o acento "Ocorrencias", na página de visualização, cadastro e edição de ocorrências de um aluno.
![image](https://cloud.githubusercontent.com/assets/1082624/8878011/10097e00-31ff-11e5-8734-67fb1487e31b.png)

SOLUÇÃO:
- [x] Aplicar as correções gramaticais para a palavra "ocorrencia": "Ocorrência".

OBSERVAÇÕES:
Não se aplica

**Comment by carolinesalib** [comment]
Olá!

* Foram corrigidos alguns erros gramaticais no cadastro/detalhes de aluno e ocorrências disciplinares.

Esta alteração estará disponível no próximo deploy previsto para 31/08/2015 e poderá ser conferida no ambiente de demonstração da Comunidade no endereço https://portal.softwarepublico.gov.br/social/i-educar
