### ISSUE TITLE
Criar uma forma de facilitar a localização do usuário no sistema

### ISSUE THREAD

**Issue by giovanibl** [portabilis/ieducar#15]
MENU:
Todos os módulos do i-Educar:
Módulo i-Educar - Agenda;
Módulo i-Educar - DRH;
Módulo i-Educar - Endereçamento;
Módulo i-Educar - Biblioteca;
Módulo i-Educar - Escola;
Módulo i-Educar - Pessoa F/J;
Módulo i-Educar - Principal;

PROBLEMA:
Atualmente, ao acessar um determinado cadastro em qualquer módulo disponibilizado, o sistema não indica a localização atual do usuário, nem ao menos informa o título do cadastro em que o mesmo se encontra. Trata-se de uma questão de usabilidade do sistema, que deve ser aperfeiçoada

SOLUÇÃO:
É necessário exibir o título de cada cadastro. O título do menu onde o usuário se encontra deve ser exibido imediatamente abaixo do menu suspenso, tanto em modo Listagem, Detalhe, quanto Edição de cada cadastro.

A sugestão é utilizar o próprio título dado ao cadastro nas permissões do usuário em DRH >> Funcionários, as quais caso não estejam descritas de forma objetiva ao cadastro, poderão ser reescritos mediante uma alteração, já que os nomes dos menus ficam gravados em tabelas do banco de dados.

OBSERVAÇÃO:
Uma sugestão adicional a esta da solução seria mostrar o caminho completo de localização do cadastro dentro do sistema, ou seja, caso estivesse acessando o cadastro de alunos, em i-Educar - Escola >> Cadastros > Aluno > Alunos, apresentaria assim:

i-Educar - Escola >> Cadastro de Alunos

**Comment by giustin** [comment]
Olá!

Esta issue está sendo finalizada pois foi atendida parcialmente e agora estamos apresentando uma nova proposta de design e aplicando o recurso em todo o sistema na issue #146 [1].

[1] https://github.com/portabilis/ieducar/issues/146
