### ISSUE TITLE
Aumentar tamanho do campo Áreas de conhecimento utilizados pelos componentes curriculares

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#150]
MENU:
i-Educar Escola > Componentes Curriculares > Áreas de Conhecimento

PROBLEMA:
Atualmente o campo Área de conhecimento tem um limite de 40 caracteres.

SOLUÇÃO:
- [x] Aumentar o tamanho do campo na interface, e se necessário, no banco de dados para 60 caracteres.

OBSERVAÇÕES:
Não se aplica

**Comment by carolinesalib** [comment]
Olá!

* Foi aumentado o tamanho do campo "Área de conhecimento" para que possa ser cadastrada uma área de conhecimento com até 60 carácteres.

Esta alteração estará disponível no próximo deploy previsto para 16/09/2015 e poderá ser conferida no ambiente de demonstração da Comunidade no endereço https://portal.softwarepublico.gov.br/social/i-educar
