### ISSUE TITLE
Aprimorar seção de endereçamento para busca e cadastro rápido de endereços no cadastro de pessoas

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#151]
MENU:
Endereçamento
i-Educar Escola > Cadastros > Alunos > Cadastrar

PROBLEMA:
Atualmente obrigamos a todos os usuários montarem os endereços manualmente no módulo Endereçamento e no cadastro de cada pessoa usar a lupa para buscar um endereço.

Ocorre que temos vários problemas e motivações para rediscutir este processo no sistema:

* Conversões de sistemas legados que crie registros incorretos da base antiga e temos alunos no mesmo endereço mas usando cadastro diferentes;
* Bloquear o usuário de informar um endereço diretamente tem sido indesejável pelos mesmos, muito embora saibamos do benefícios de extração de informação por determinados endereços mais tarde;
* O cadastro de novos endereços é lento e difícil de realizar;
* O usuário ao tentar informar um endereço, é obrigado a usar lupa que é mais uma tarefa dentro do cadastro que consome tempo (ex.: preencher o CEP, não preenche automático os campos)

SOLUÇÃO:
Analisar uma possível solução de integração com o Web service dos correios ou carga de dados de endereço de todo o Brasil no banco de dados de modo que seja possível o usuário buscar informações pelo logradouro, CEP, etc, e buscar tanto na sua base de dados quanto via Web service.

Algumas questões e sugestões que podem ser levadas em consideração:

* Facilitar a digitação dos endereços no cadastro de pessoas, usando recursos como o simple search (auto complete) e/ou preenchendo campos automaticamente (ex seleciona e carrega próximo campo), sem precisar ir até outro cadastro/lupa;
* Criar uma seção exclusiva para agrupar os campos de endereçamento, contendo um texto de ajuda para auxiliar os usuários;
* Avaliar o design da nova seção de endereçamento das pessoas, de forma que torne mais rápido a busca, inserção e atribuição de endereço as pessoas.

OBSERVAÇÕES:
Web API aparentemente pronta, gratuita, e sincronizada com o a base dos Correios:
http://avisobrasil.com.br/correio-control/api-de-consulta-de-cep/
Outras referências:
http://www.buscacep.correios.com.br/
http://www.pinceladasdaweb.com.br/blog/2012/01/31/webservice-consulta-de-cep-diretamente-ao-site-dos-correios/

**Comment by carolinesalib** [comment]
Olá!

Uma observação:
Para desenvolvimento dessa issue, será retirado a utilização do parâmetro que permite cadastrar novo endereço a partir do cadastro de pessoa física, cuja alteração foi desenvolvida através da issue:
https://github.com/portabilis/ieducar/issues/50

**Comment by carolinesalib** [comment]
Alterações realizadas no cadastro de pessoa física:

1. Adicionado rótulo <b>Endereçamento</b> com texto explicativo para dividir seção;
2. Modificado o campo <b>CEP</b> para funcionar da seguinte maneira:
 * O usuário continua podendo fazer uma busca avançada utilizando a lupa; 
 * O campo é aberto para o usuário digitar o CEP manualmente. Caso seja encontrado, o sistema buscará dados do primeiro CEP que encontrar e preencherá o resto dos dados (Logradouro/Bairro). Caso não seja encontrado, os campos serão desbloqueados para que o usuário preencha.
3. Adicionado o campo _SimpleSearchLogradouro_ no campo <b>Tipo/Logradouro</b> permitindo que o usuário busque um Logradouro e "monte" seu endereço. O campo pode ser alternado para o campo de cadastro clicando no link à direita;
4. Adicionado o campo _SimpleSearchBairro_ no campo <b> Bairro/Zona de localização</b> que se comporta similar ao item <b>3</b>;
5. Anteriormente quando o usuário cadastrava um endereço novo, o mesmo era salvo em uma tabela chamada *endereco_externo*, que isolava esses endereços dos endereços padrões, impedindo que fossem feito quaisquer  estatística sobre alunos/endereço/moradia, ou qualquer outro tipo de proveito que pudesse ser tirado dessas informações. Agora ao salvar um endereço, seja ele contido de campos novos ou mistos (dados novos e dados pesquisados) todos os dados novos são cadastrados e o endereço é salvo na tabela padrão. Mesmo que os usuários optem por não buscar o endereço e cadastre dados duplicados, não seria tão difícil uma rotina de unificação desses dados posteriormente.
6. Retirada a obrigatoriedade do endereçamento: O sistema agora só irá validar o endereçamento caso o mesmo esteja incompleto, se estiver completamente vazio a pessoa poderá ser salva sem problemas. _OBS: Não considera os campos de complemento._.

**Comment by carolinesalib** [comment]
Olá,

alterações disponíveis para visualização no ambiente: http://comunidade.ieducar.com.br/

Esta tarefa também foi replicada e disponibilizada no ambiente oficial da Comunidade i-Educar. Para mais informações, acesse https://softwarepublico.gov.br/gitlab/i-educar/i-educar/issues/7.
