### ISSUE TITLE
Adicionar campo seção no cadastro de áreas de conhecimento

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#152]
MENU:
i-Educar Escola > Componentes Curriculares > Áreas de Conhecimento

PROBLEMA:
Atualmente não existe um campo para a seção de uma Área de conhecimento. Uma área de conhecimento pode ter o nome por exemplo de "Ciências da natureza" e uma seção que abrange por exemplo "Lógico Matemático". 

Estas informações são necessárias para a organização das áreas de conhecimento e seu uso em outras áreas do sistema e relatórios.

SOLUÇÃO:
- [x] Adicionar campo Seção no cadastro de Áreas de conhecimento.

OBSERVAÇÕES:
Não se aplica

**Comment by carolinesalib** [comment]
Olá!

Alteração realizada e disponível para acessos em: http://comunidade.ieducar.com.br/
