### ISSUE TITLE
Aprimorar filtro de busca por tipo de usuário para retornar apenas usuários ativos

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#153]
MENU:
i-Educar Escola > Administrativo > Usuários

PROBLEMA:
Atualmente, no filtro de busca 'Tipo Usuário' estão sendo listados tipos de usuários excluídos.

SOLUÇÃO:
- [x] Altera a busca por tipo de usuário para exibir na listagem somente os usuários ativos.

OBSERVAÇÕES:
Não se aplica

**Comment by carolinesalib** [comment]
Olá!

* Foi alterado para que no filtro "Tipo de usuário" no cadastro de usuários apareça somente usuários com cadastro ativo.

Esta alteração estará disponível no próximo deploy previsto para 30/09/2015 e poderá ser conferida no ambiente de demonstração da Comunidade no endereço https://portal.softwarepublico.gov.br/social/i-educar
