### ISSUE TITLE
Aprimorar seleção de informações e o processamento da funcionalidade de rematrícula automática

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#154]
MENU:
i-Educar Escola > Movimentação > Rematricula Automática

PROBLEMA:
Ao efetuar o processo de rematricula são apresentados na listagem todos os alunos da turma, após isso, na mesma janela, ao tentar efetuar um novo processo pode ser verificado que as turmas do ano anterior não são carregadas.

Também já foi relatado por outros usuários anteriormente que ao processar a rematricula automática, aparentemente o sistema estaria efetuando a rematricula de todas as turmas, mesmo sem seleção.

SOLUÇÃO:
- [ ] Aprimorar o processo de rematrícula automática para que trate corretamente os filtros de seleção da turma e não execute processos em dados sem a pré-seleção do usuário.

OBSERVAÇÕES:
Não se aplica

**Comment by carolinesalib** [comment]
Olá, @giustin!

Disponível para teste.

**Comment by carolinesalib** [comment]
Olá, @giustin!

Estava testando o waffle.io e não percebi que tinha fechado.

**Comment by giustin** [comment]
Olá, @carolinesalib !

Testes OK.

Pode disponibilizar no ambiente da Comunidade do i-Educar, por favor.

**Comment by carolinesalib** [comment]
Olá!

Disponível no ambiente:
http://comunidade.ieducar.com.br/

Issue na comunidade:
https://softwarepublico.gov.br/gitlab/i-educar/i-educar/issues/11
