### ISSUE TITLE
Aprimorar o cadastro e edição de alunos e responsáveis para ser mais fácil e ágil

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#155]
MENU:
i-Educar Escola > Cadastros > Alunos > Cadastrar

PROBLEMA:
Desde que uma alteração pela Portabilis foi feita para permitir cadastrar aluno, pai, mãe e responsável como pessoa, tornamos padrão e normalizado os dados, porém, também tornamos o processo de cadastro de novos alunos lento e complexo.

O cadastro de alunos é, segundo estatísticas que monitoramos, o mais usado por todos os nossos clientes todos os dias, portanto, faz-se necessário uma melhoria significativa nesta funcionalidade para facilitar ao usuário.

SOLUÇÃO:
Analisar e projetar um novo recurso para o cadastro de alunos, pais e responsáveis onde seja possível atender as seguintes necessidades e motivações:

* Possibilitar cadastrar o aluno na mesma tela, usando ajax ou alguma modal, de forma que se seja passado ao sistema somente os campos obrigatórios, e os demais, se o usuário desejar, poderá acessar depois e completar;
* Aplicar a mesma sistemática para pais e responsáveis, dados de transporte escolar e endereçamento;
* Oferecer opções de cadastro e edição rápida e adicionalmente na modal, exibir uma opção para acessar o cadastro completo, levando para forma de cadastro atual em nova aba;
* Campo do aluno, pai e mãe podem ser tratados como um simple search (auto complete) nos campos atuais da página e se o usuário não encontrar pesquisando pelo mesmo, pode usar a opção de cadastro rápido. 
* Avaliar viabilidade de adicionar a seção de endereçamento que foi remodelada dentro da mesma modal para cadastro rápido de alunos.

Mockup inicialmente desenvolvida para orientar o desenvolvimento:
![image](https://cloud.githubusercontent.com/assets/1082624/8879689/5f118cd6-3209-11e5-89af-18b5f32c01b0.png)

OBSERVAÇÕES:
Não se aplica

**Comment by carolinesalib** [comment]
Olá, @giustin!

Disponível para teste.

**Comment by giustin** [comment]
Olá, @carolinesalib !

Testes OK. Ficou excelente a alteração!

Pode disponibilizar no ambiente da Comunidade do i-Educar, por favor.

Imagens das alterações para conferência de quem acompanha esta tramitação:

![image](https://cloud.githubusercontent.com/assets/1082624/15402578/575b4c30-1dcb-11e6-9d8f-d69945e8d6a9.png)
![image](https://cloud.githubusercontent.com/assets/1082624/15402584/61a176b0-1dcb-11e6-967c-687931debe0c.png)
![image](https://cloud.githubusercontent.com/assets/1082624/15402592/6a127466-1dcb-11e6-847e-0b2328273cd9.png)

**Comment by carolinesalib** [comment]
Olá!

Disponível no ambiente:
http://comunidade.ieducar.com.br/

Issue na comunidade:
https://softwarepublico.gov.br/gitlab/i-educar/i-educar/issues/12
