### ISSUE TITLE
Corrigir problema no processo de cancelamento de matrícula de alunos

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#156]
MENU:
i-Educar Escola > Cadastros > Alunos > Cadastrar

PROBLEMA:
Foi verificado em vários clientes que alguns alunos com matrícula cancelada geram problema no campo ```ultima_matricula``` da tabela ```pmieducar.matricula```, sendo esta setada para o valor 0 (zero) e o aluno ativo e tendo outro registro com o aluno desativado e com o campo ultima_matricula = 1. 

Com isso o aluno com tal situação pode não ser apresentado corretamente em algumas funcionalidades ou relatórios.

SOLUÇÃO:
- [ ] Corrigir o processo de cancelamento de matrícula, para que ao cancelar uma matrícula seja setado o campo ultima_matricula para o valor 0.

OBSERVAÇÕES:
Não se aplica

**Comment by carolinesalib** [comment]
Olá, @giustin!

Disponível para teste.

Obs.: Para realização deste teste, será necessário acesso ao banco, você poderá utilizar o software PgAdmin3 para facilitar o acesso. Qualquer dúvida sobre como utilizar este software quando o i-Educar estiver rodando via Vagrant pode me chamar.

**Comment by giustin** [comment]
Olá, @carolinesalib !

Testes OK. Pode ser transferido para a Comunidade.

Obrigado.
