### ISSUE TITLE
Alterar processos da matrícula e outras funcionalidades de deslocamento e remanejamento para atendimento aos municípios de SP que usam o PRODESP/GDAE

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#157]
MENU:
i-Educar Escola > Cadastros > Alunos > Cadastrar
i-Educar Escola > Movimentação > Faltas/notas
Outras funcionalidades relacionadas

PROBLEMA:
Atualmente o sistema não atende alguns controles de deslocamento de alunos necessários para se adequar aos clientes do estado de SP, que utilizam o sistema PRODESP/GDAE, como o exemplo do município de Botucatu/SP, que usa o i-Educar.

SOLUÇÃO:
Criar campos **_Data base máxima para deslocamento**_ e **_Data base máxima para troca de sala**_ nos parâmetros na instituição, funcionando da seguinte maneira:

**_Data base máxima para deslocamento:**_

Afetará a listagem no lançamento de notas e relatórios que existirem ou forem desenvolvidos no futuro, exemplos, Diários do professor, Mapa do conselho de classe, Resultado final, etc, sendo que ao ser realizadas transferências APÓS esta data o aluno continuará sendo exibido na listagem, porém, com algum estilo que o diferencie dos demais, sigla TRANSF e, no caso da funcionalidade de lançamento de notas, sem a possibilidade de lançar notas para essa matrícula.

**_Data base máxima para troca de sala:**_

Afetará a listagem no lançamento de notas e também relatórios, sendo que ao ser cancelado a matrícula/turma de um aluno APÓS esta data o aluno continuará sendo exibido na listagem, porém com algum estilo que o diferencie dos demais, com a sigla REM e, no caso da funcionalidade de lançamento de notas, sem possibilidade de lançar notas pra essa matrícula.

Efetuar também as seguintes alterações:
- Criado parâmetro de configuração na instituição para que os municípios de São Paulo que desejarem trabalhar desta forma possam habilitar este recurso;
- Modificar os processos matrícula, enturmação individual, transferência externa e interna, enturmação em lote para auxiliar este controle;
- Alterar a interface de lançamento e notas e possíveis relatórios para que quando o aluno for transferido ou remanejado após a respectiva data base deverá ir para o fim da lista, funcionando em paralelo com a data de fechamento (Issue que criou este recurso: https://github.com/portabilis/ieducar/issues/114) do cadastro de turmas;

OBSERVAÇÕES:
Não se aplica

**Comment by carolinesalib** [comment]
Olá, @giustin!

Disponível para teste.

Para atualizar o banco utilizando vagrant siga os passos a seguir:

> vagrant ssh
> vendor/bin/phinx migrate -e development

**Comment by giustin** [comment]
Olá, @carolinesalib !

Funcionalidade OK. Disponível em http://comunidade.ieducar.com.br.

Issue na comunidade: https://softwarepublico.gov.br/gitlab/i-educar/i-educar/issues/14
