### ISSUE TITLE
Corrigir problema ao salvar as disciplinas (componentes curriculares) no cadastro de turma

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#158]
MENU:
i-Educar - Escola > Cadastros > Turma > Editar uma turma

PROBLEMA:
Algumas vezes, ao selecionar os componentes curriculares na Turma - para utilizar componentes diferentes do padrão da série-escola - ocorre o seguinte erro:

```
Erro ao executar uma ação no banco de dados: SQL invalido:_ `INSERT INTO modules.componente_curricular_turma (componente_curricular_id, ano_escolar_id, escola_id, turma_id, carga_horaria) VALUES ('5', NULL, NULL, '385', NULL)
```
SOLUÇÃO:
- [ ] Verificar a causa do problema e tratar o erro para que seja possível definir os componentes curriculares na turma sem falhas.

OBSERVAÇÕES:
Não se aplica

**Comment by carolinesalib** [comment]
Olá, @giustin!

Disponível para teste.

**Comment by giustin** [comment]
Olá @carolinesalib !

Testes OK. Obrigado!

**Comment by carolinesalib** [comment]
Olá!

Disponível em http://comunidade.ieducar.com.br.
