### ISSUE TITLE
Controle das notas e componentes curriculares dos alunos quando for excluído da série e/ou turma

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#159]
MENU:
i-Educar - Escola > Cadastros > Componentes Curriculares > Listar Componentes > Configurar anos escolares

PROBLEMA:
Atualmente se um componente curricular for desabilitado para uma série e tenha notas lançadas para algum aluno matriculado nesta série pode ocorrer problema de integridade dos dados. No caso o componente permanece oculto no aluno com a nota ou falta lançada, com isso o usuário não sabe porque a situação do aluno fica incorreta.

SOLUÇÃO:
- [x] Aprimorar este processo para que quando um aluno enturmado possuir dados lançados nas disciplinas vinculadas na série, série-escola ou turma e estes forem alterados, as notas sejam tratadas para que o aluno não fique com a situação incorreta.

OBSERVAÇÕES:
Não se aplica

**Comment by carolinesalib** [comment]
Olá, @giustin!

Disponível para teste.

**Comment by giustin** [comment]
Olá, @carolinesalib !

Task OK. Disponível em http://comunidade.ieducar.com.br.

Issue na comunidade: https://softwarepublico.gov.br/gitlab/i-educar/i-educar/issues/16
