### ISSUE TITLE
[Bug] Parâmetro duplicado

### ISSUE THREAD

**Issue by dudemelo** [portabilis/ieducar#169]
O parâmetro ``$int_idmun`` do método [``listamun``](https://github.com/portabilis/ieducar/blob/master/ieducar/intranet/include/pessoa/clsLogradouro.inc.php#L237) está duplicado.

```php
	function listamun( $str_idtlog=false, $str_nome=false, $int_idmun=false, $int_idmun=false, $str_geom=false, $str_ident_oficial=false, $int_limite_ini=0, $int_limite_qtd=20, $str_orderBy = false )

...
		if( is_numeric( $int_idmun ) )
		{
			$where .= "{$whereAnd}idmun = '$int_idmun'";
			$whereAnd = " AND ";
		}
		if( is_numeric( $int_idmun ) )
		{
			$where .= "{$whereAnd}idmun = '$int_idmun'";
			$whereAnd = " AND ";
		}
...
```

**Comment by giustin** [comment]
Olá, @dudemelo ! Obrigado por reportar.

@carolinesalib, você pode verificar se o problema ainda persiste e caso sim, criar uma tarefa no ambiente da Comunidade para corrigirmos lá também?

**Comment by carolinesalib** [comment]
Tarefa replicada no repositório Gitlab do Portal do SPB: https://softwarepublico.gov.br/gitlab/i-educar/i-educar/issues/29

**Comment by carolinesalib** [comment]
Olá!

Parâmetro duplicado removido.

**Comment by dudemelo** [comment]
Parâmetro duplicado na assinatura do método gera um **fatal error**. Fiz uma breve pesquisa e não encontrei outro ponto do código fazendo uso deste método, ele é realmente necessário?

**Comment by carolinesalib** [comment]
Olá, @dudemelo!

Eu não entendi, você está chamando o método "listamun()" em algum lugar e está gerando um fatal error? Porque realmente, ele não é usado em nenhum outro lugar... :disappointed:

**Comment by dudemelo** [comment]
A simples declaração do método com parâmetro duplicado já gera um fatal error. Que tal removermos este método, já que não está sendo usado em lugar algum?? :smile:

**Comment by carolinesalib** [comment]
@dudemelo, tens razão, eu não havia notado que o parâmetro estava duplicado na declaração também, falha minha... Vou reabrir a issue para que a function seja removida. :relaxed:

**Comment by carolinesalib** [comment]
Olá, @dudemelo cc/ @giustin!

Método removido, estarei encerrando a issue. :smile:
