### ISSUE TITLE
Remover links para produtos em sites externos na tela de login que não fazem parte do i-Educar

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#170]
MENU:
Tela de login do sistema

DESCRIÇÃO:
Atualmente na tela de login do i-Educar possuímos os seguintes links, mais precisamente no quadro de Matrícula e Senha:

Esqueceu sua senha?
Acesso professores, pais e alunos.
Saiba mais
Os 2 últimos apontam para produtos satélites do i-Educar da Portabilis que não são de código-aberto. Sendo assim, precisamos alterar e remover estes links da tela de login da versão oficial da Comunidade.

OBSERVAÇÕES:
Não se aplica

**Comment by giustin** [comment]
Olá! 

Esta tarefa foi replicada para a lista de tarefas da plataforma da Comunidade i-Educar:
https://softwarepublico.gov.br/gitlab/i-educar/i-educar/issues/24

**Comment by carolinesalib** [comment]
Olá!

Alteração realizada e já disponível em http://comunidade.ieducar.com.br
