### ISSUE TITLE
Erro de SQL column sus does not exist ao tentar acessar o sistema após a instalação 

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#172]
**MENU:**
Tela de login

**DESCRIÇÃO:**
Alguns usuários relataram por e-mail que estão tendo o seguinte problema ao acessar o sistema, após ter feito a instalação seguindo os passos da documentação.
```
Erro app Erro ao executar uma ação no banco de dados: SQL invalido: SELECT idpes, data_nasc, sexo, idpes_mae, idpes_pai, idpes_responsavel, idesco, ideciv, idpes_con, data_uniao, data_obito, nacionalidade, idpais_estrangeiro, data_chegada_brasil, idmun_nascimento, ultima_empresa, idocup, nome_mae, nome_pai, nome_conjuge, nome_responsavel, justificativa_provisorio, cpf , ref_cod_religiao, sus, nis_pis_pasep FROM cadastro.fisica WHERE idpes = 1 Erro php pg_query(): Query failed: ERROR: column "sus" does not exist LINE 1: ...justificativa_provisorio, cpf , ref_cod_religiao, sus, nis_p... ^ Arquivo (linha: 434) /home/educacao/ieducar/ieducar/intranet/include/clsBancoPgSql.inc.php
```
O problema pode estar relacionado a alguma atualização recente do cadastro de pessoas e alunos.

**OBSERVAÇÕES:**
Problema relatado por usuários diretamente para a Portabilis por e-mail.

**Comment by giustin** [comment]
Olá!

Esta tarefa foi replicada para a lista de tarefas do projeto i-Educar no repositório oficial, do Portal do Software Público. Para mais informações, acesse: https://softwarepublico.gov.br/gitlab/i-educar/i-educar/issues/28

**Comment by carolinesalib** [comment]
Olá, @giustin!

Para resolver este problema, basta fazer uma atualização no banco de dados através do comando abaixo, também disponibilizado no guia de Atualização do i-Educar na wiki do Portal do SPB [1].

> curl -L https://gist.githubusercontent.com/portabilisgist/640cf3311ef47947f628/raw/77823a74fb14dababbf0a3a4ae7ca4ec1c2be765/ieducar_migracoes_a_partir_53.sh | bash

[1] https://softwarepublico.gov.br/gitlab/i-educar/i-educar/wikis/atualizacao-ieducar-ubuntu
