### ISSUE TITLE
É exibido uma tela em branco ao tentar abrir o calendário letivo

### ISSUE THREAD

**Issue by carolinesalib** [portabilis/ieducar#174]
**MENU:**
i-Educar - Escola > Cadastros > Calendário Letivo > Calendários

**DESCRIÇÃO:**
Ao tentar abrir a tela "Calendários" no menu "Calendário Letivo" é apresentado uma tela em branco.

**OBSERVAÇÕES:**
Issue na comunidade: https://softwarepublico.gov.br/gitlab/i-educar/i-educar/issues/36

**Comment by carolinesalib** [comment]
Olá, @giustin!

Ajustado, favor verificar no ambiente comunidade.ieducar.com.br.

**Comment by giustin** [comment]
Olá, @carolinesalib ! Testes OK.
