### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by michelmarques1** [portabilis/ieducar#175]
Colegas da comunidade,

Após instalar o Ieducar no Windows, o mesmo me retorna o seguinte erro:

Warning: require_once(Mail.php): failed to open stream: No such file or directory in C:\xampp\htdocs\sistemas\academico\ieducar-master\ieducar\lib\Portabilis\Mailer.php on line 44

Fatal error: require_once(): Failed opening required 'Mail.php' (include_path='C:\xampp\htdocs\sistemas\academico\ieducar-master\ieducar\intranet;C:\xampp\htdocs\sistemas\academico\ieducar-master\ieducar\lib;C:\xampp\htdocs\sistemas\academico\ieducar-master\ieducar\modules;C:\xampp\htdocs\sistemas\academico\ieducar-master\ieducar\.;C:\xampp\php\PEAR') in C:\xampp\htdocs\sistemas\academico\ieducar-master\ieducar\lib\Portabilis\Mailer.php on line 44

Poderiam me ajudar?

**Comment by giustin** [comment]
Olá, @michelmarques1 ! cc @carolinesalib !

O i-Educar não é compatível nativamente com o Windows. :( Mas, existem opções de instalação para outros sistemas operacionais e via Vagrant para Windows.

Peço que acesse o tutorial de instalação oficial da Comunidade neste link abaixo, e se tiver algum problema ou dúvida, relate na lista de discussão:

Link geral sobre instalação:
https://softwarepublico.gov.br/social/i-educar/tutorial-de-instalacao

Link direto para as diversas maneiras:
https://softwarepublico.gov.br/gitlab/i-educar/i-educar/wikis/install-ieducar

Link para a lista de discussão:
https://softwarepublico.gov.br/gitlab/i-educar/i-educar/wikis/como-se-inscrever-e-participar-das-listas

Obrigado.
