### ISSUE TITLE
[Bug] Área de Conhecimento - Erro Inesperado

### ISSUE THREAD

**Issue by michelmarques1** [portabilis/ieducar#176]
Olá colegas da comunidade, tudo bem?

Realizei a instalação do Ieducar via vagrant. Consegui realizar algumas inserções. Contudo, quando tento inserir uma Área de Conhecimento o mesmo me retorna o seguinte erro:

Erro inesperado
Desculpe-nos, algum erro inesperado ocorreu, tente seguir as etapas abaixo:
Tente novamente
Faça logoff do sistema e tente novamente
Caso o erro persista, por favor, solicite suporte.
Detalhes:

Erro app
Erro ao executar uma ação no banco de dados: SQL invalido: SELECT id, instituicao_id, nome, secao FROM modules.area_conhecimento WHERE 1 = 1 

Erro php
pg_query(): Query failed: ERROR: column "secao" does not exist LINE 1: SELECT id, instituicao_id, nome, secao FROM modules.area_con... ^
Arquivo
(linha: 434) /home/vagrant/ieducar/ieducar/intranet/include/clsBancoPgSql.inc.php

O que será que pode ser?

**Comment by michelmarques1** [comment]
Prezados, boa noite

Só realizando um adendo, realizei outra instalação, em uma VM, Ubuntu 12.04 e o erro persiste.

**Comment by giustin** [comment]
Olá, @michelmarques1 ! Tudo bem?

Para este problema, já existe uma discussão com resolução na lista da Comunidade, veja:
https://softwarepublico.gov.br/archives/thread/i-educar/re-criacao-e-acesso-ao-banco

Peço a gentileza que antes de abrir uma issue, tente usar a lista de discussão para pesquisar ou perguntar, pois sua dúvida pode ser a dúvida de outro.

Obrigado pela compreensão.

Obs.: Este repositório é administrado pela Portabilis e o repositório oficial, onde você pode obter ajuda não só da Portabilis mas também de outros membros e empresas, é na Comunidade i-Educar [1], no Portal do SPB, no seguinte endereço:
https://portal.softwarepublico.gov.br/social/i-educar

Abs!!

**Comment by carolinesalib** [comment]
Olá, @michelmarques1!

Siga os passos abaixo para criar o campo secao na tabela de area de conhecimento usando vagrant:

> vagrant ssh
> ~/.pgvm/environments/8.2.23/bin/psql -d ieducar -p 5433 -c "ALTER TABLE modules.area_conhecimento ADD COLUMN secao CHARACTER VARYING(50);"
> exit

Referencia:
https://github.com/portabilis/ieducar/issues/152
