### ISSUE TITLE
Problemas na instalação inicial

### ISSUE THREAD

**Issue by twisterbr** [portabilis/ieducar#180]
Baixei a versão v1.1.0 que creio que seja a atual (baixado de https://softwarepublico.gov.br/social/i-educar), segui orientações do README.txt mas não está dando certo. Toda hora que tento logar acusa que está faltando tabelas ou colunas no banco.

Sei que tem os tais deltas e portabilis, mas ainda não entendi como devo instalá-los. Pra falar a verdade achei isso tudo meio atrapalhado, porque eu descobri esse detalhe pesquisando, já que nem tem essa informação no README.

De qualquer forma, como indicado pelo readme, restaurei o banco misc/database/ieducar.sql, e em seguida restaurei todos os sqls dos deltas e portabilis, mas dá muito erro e não consigo logar na aplicação (admin/admin).

Monitorando pelo error.log, a aplicação acusa a tabela com problema. O que estou fazendo é procurar nos sql onde tem o create table e rodo na mão, mas tá muito inviável ficar fazendo isso com cada erro que aparece.
Qual a melhor forma de instalar? Ou não tem forma prática?

Obrigado!

Meu postgres é o 9.1.

**Comment by twisterbr** [comment]
Tentei de outra forma agora. Formatei o servidor, instalei ubuntu 12.04 (era 14.04) e rodei o install-ieducar.sh. Está dando erro no passo do restore do banco:
ERROR:  role "vagrant" does not exist
STATEMENT:  REVOKE ALL ON SCHEMA public FROM PUBLIC;
	REVOKE ALL ON SCHEMA public FROM vagrant;
	GRANT ALL ON SCHEMA public TO vagrant;
	GRANT ALL ON SCHEMA public TO PUBLIC;
	
	
	
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 5673; 0 0 ACL public vagrant
pg_restore: [archiver (db)] could not execute query: ERROR:  role "vagrant" does not exist
    Command was: REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM vagrant;
GRANT ALL ON SCHEMA public TO vagrant;
GR...
WARNING: errors ignored on restore: 1

Alguma luz?

**Comment by giustin** [comment]
Olá, @twisterbr ! Tudo bem?

Todo documentação que contribuímos na Comunidade está listada neste local:
https://softwarepublico.gov.br/gitlab/i-educar/i-educar/wikis/home

Na opção "Como instalar o i-Educar", você terá pelo menos 3 opções de instalação, passo a passo ou com um único comando.

Se você não obtiver sucesso, por favor, relate a sua dificuldade, sugestão ou crítica para a lista de discussão da Comunidade, que é o canal oficial para todos os membros.
https://softwarepublico.gov.br/gitlab/i-educar/i-educar/wikis/como-se-inscrever-e-participar-das-listas

Obs.: lembrando que o i-Educar ainda não está homologado para a versão 9 do PostgreSQL. Aqui neste tópico discutimos sobre isto neste ano em um hangout com a Comunidade:
https://softwarepublico.gov.br/archives/thread/i-educar/convite-atualizacao-1o-ieducarlive-encontro-tecnico-da-comunidade-i-educar-ao-vivo

Obrigado pela compreensão.
