### ISSUE TITLE
Problema ao cadastrar novas turmas

### ISSUE THREAD

**Issue by portabilisgist** [portabilis/ieducar#181]
MENU:
i-Educar - Escola / Cadastro / Turma

PROBLEMA:
Alguns usuários tem relatado que tem dificuldades ao cadastrar novas turmas, pois o campo de escola não está sendo apresentado para que se possa selecionar.

SOLUÇÃO:

- [x] Corrigir para que sempre seja apresentado o campo escola.

OBSERVAÇÕES:
Não se aplica.

**Comment by carolinesalib** [comment]
Olá!

Tarefa na comunidade: https://softwarepublico.gov.br/gitlab/i-educar/i-educar/issues/41
