### ISSUE TITLE
Erro nas consultas

### ISSUE THREAD

**Issue by rodrigoalexandrino** [portabilis/ieducar#186]
Bom dia, quando vou fazer alguma consulta está dando esse erro do anexo, nesse exemplo é na consulta de alunos, mas o mesmo se repete em todas as buscas.

![captura de tela 2017-05-04 as 15 59 08](https://cloud.githubusercontent.com/assets/11276345/25745746/d1fd3f24-3176-11e7-91ab-bafcc905d91e.png)

**Comment by giustin** [comment]
Olá, @rodrigoalexandrino !

Obrigado por relatar este problema. 

Acessei o sistema no ambiente da Comunidade (comunidade.ieducar.com.br) e não identifiquei esta falha. Você fez a instalação seguindo os passos descritos na instalação oficial (https://softwarepublico.gov.br/gitlab/i-educar/i-educar/wikis/install-ieducar)?

Vou encerrar a tarefa e se você tiver alguma dificuldade, por favor, relate primeiro na Lista de discussão, para que a Comunidade analise e então possamos ajustar, se for possível simular o problema. 

O local correto para relatar as issues da Comunidade é aqui:
https://softwarepublico.gov.br/gitlab/i-educar/i-educar/wikis/como-contribuir#como-criar-uma-issue

Estamos em fase de migração para a versão 9 do Postgres e a lista das tarefas pendentes para fazer você pode conferir neste link:
https://softwarepublico.gov.br/gitlab/i-educar/i-educar/issues

Obrigado.
