### ISSUE TITLE
Adotar biblioteca Jasper Reports for PHP como fábrica de relatórios para o i-Educar em substituição ao PHPJasperXML

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#193]
MENU:
Todos os relatórios
Descontinuidade Projeto PHPJasperXML

PROBLEMA:
Conforme relatado na issue #67, havíamos planejado atualizar o projeto PHPJasperXML, para dar suporte a alguns recursos novos para relatórios. Porém, aparentemente o projeto PHPJasperXML estaria sendo descontinuado, pelo menos juntos aos desenvolvedores originais, e então não faz mais sentido mantê-lo no projeto.

SOLUÇÃO
Como solução a este problema, planejamos adotar [Jasper Reports for PHP](https://github.com/cossou/JasperPHP) como fábrica de relatórios oficial para i-Educar:

 - [ ] Adotar o projeto Jasper Reports for PHP como fábrica de relatórios oficial do i-Educar, mantendo a fábrica atual com PHPJasperXML funcionando para fins de compatibilidade, para relatórios que por ventura foram desenvolvidos por utilizadores e precisam deste suporte;

Tarefa futura (podemos criar depois que concluirmos o item acima):

- [ ] Migrar todos os relatórios atuais escritos para PHPJasperXML para a nova fábrica Jasper Reports for PHP.

OBSERVAÇÕES:
Referências do PHPJasperXML: https://github.com/portabilis/ieducar/issues/67

**Comment by giustin** [comment]
Olá, @carolinesalib ! 

Issue na Comunidade: https://softwarepublico.gov.br/gitlab/i-educar/i-educar/issues/66

**Comment by carolinesalib** [comment]
Olá!

Atualização realizada.

Instruções para que os relatórios funcionem corretamente foram adicionadas no guia de instalação:
https://softwarepublico.gov.br/gitlab/i-educar/i-educar/wikis/instalacao-ieducar#instalando-dependencias-para-relat-rios-jasper
