### ISSUE TITLE
Importação/Exportação Censo Escolar

### ISSUE THREAD

**Issue by uitalloferreira** [portabilis/ieducar#197]
Percebo que este repositório está mais atualizado do que os demais, minha dúvida é se ele disponibiliza esta integração com Censo Escolar.
Obrigado

**Comment by caddago** [comment]
Olá, @uitalloferreira! Como vai? Ainda não está totalmente implementada tal funcionalidade, estamos gradativamente ajustando os cadastros para inserção dessa funcionalidade.

**Comment by giustin** [comment]
Olá, @uitalloferreira !

Nós mantemos este repositório sincronizado com o repositório oficial da Comunidade (https://softwarepublico.gov.br/gitlab/i-educar/i-educar). 

Portanto, sugiro que dúvidas ou questionamentos você possa fazer diretamente no ambiente da Comunidade, utilizando a Lista de discussão por exemplo, no endereço: https://softwarepublico.gov.br/social/i-educar

Obrigado.
