### ISSUE TITLE
Permitir informar notas numéricas com qualquer variação decimal no lançamento de notas

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#39]
MENU:
i-Educar - Escola > Movimentação > Faltas/Notas > Lançamento por turma

PROBLEMA:
Atualmente é exibida uma mensagem ao usuário quando é informado uma nota quebrada diferente da tabela de arredondamento ou de variação de valor diferente de meio ponto, por exemplo, verifique ao lançar o valor "8,8", que será exibida uma mensagem assim:

Informe um valor que pertença ao conjunto: 0, 0.5, 1, 1.5, 10, 2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5

SOLUÇÃO:
Alterar o sistema para permitir inserção de notas com qualquer valor decimal, a princípio, independentes da tabela de arrendondamento com notas, pois se tornaria inviável prever na tabela todas as possibilidades numéricas. 

Sendo assim, a tabela de arredondamento, funcionaria apenas para as notas conceituais e a numérica, poderia haver uma tabela com tipo de notas numéricas mas apenas para fins de regras de avaliação, mas tendo validade o que for informado pelo usuário.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá,

alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
