### ISSUE TITLE
Código fonte do i-Educar em inglês

### ISSUE THREAD

**Issue by edersoares** [portabilis/ieducar#400]
# Hello, community!

Agora que estamos adotando [Laravel](https://github.com/portabilis/i-educar/pull/389) como framework de desenvolvimento, surgiu uma discussão interna que gostaríamos de levar para a comunidade a fim de definirmos o idioma que iremos utilizar no código fonte, inglês ou português?

Atualmente, o código fonte do i-Educar é uma mescla dos dois idiomas, então queremos definir qual idioma iremos adotar realmente.

### Vantagens do português

- Idioma nativo da comunidade.
  - Mas os desenvolvedores em sua maioria programam em inglês.
- Nomenclaturas próprias do idioma.
  - Vamos utilizar um dicionário de termos com o intuito de padronizar o domínio.
- Banco de dados (atual).
  - Será refatorado em um futuro breve, pois está gigante.
- Público nacional.
  - Apenas o código fonte será em inglês.
- Inglês pode ser um impeditivo para contribuidores.
  - Desenvolvedores tem como "pré-requisito" o uso de inglês.
- Software Livre BR.
  - A comunidade continuará em português, apenas vamos utilizar o idioma do mercado para o código fonte.
- Maior parte do código.
  - Queremos gradativamente refatorar o código fonte, então, já mudaríamos o idioma.

### Vantagens do inglês

- Linguagem universal.
- Menos complexo.
- Linguagens de programação são em inglês.
- Frameworks e bibliotecas já utilizadas são em inglês.
- Leitura/escrita mais fluída.

#### Onde o inglês será usado?

- Nome de pastas/arquivos.
- Nome de classes, métodos e funções.
- Código fonte em geral.

#### Onde o português será usado?

- Mensagens de commits.
- Comentários.

#### Por que não usar tudo em inglês?

Acreditamos que nem todos os contribuidores que forem participar do projeto dominarão o inglês a nível de leitura, então os comentários em português facilitariam o entendimento das regras de negócio e possibilitaram referências em fóruns, FAQ, etc.

Já as mensagens de commits facilitariam a criação de releases as quais queremos manter em português e em um futuro breve se tornarem automatizadas.

### Direcionamentos

Queremos ouvir a comunidade sobre o assunto, entender se faz sentindo ou não, pois são direcionamentos que serão o padrão do i-Educar no futuro e esta é a hora de discutirmos sobre o assunto.

Obrigado a todos.

**Comment by lbssousa** [comment]
IMHO, se for para escrever código em português, só vale a pena se a linguagem suportar caracteres não-ASCII em nomes de variáveis, funções, etc. Se for para ecrever códigos como `calcula_media()` ou `executa_acao()` (e não `calcula_média()` resp. `executa_ação()`), melhor escrever em inglês mesmo.

**Comment by vinicelms** [comment]
Gosto da proposta de código em inglês e dos commits e comentários em PT-BR.

Dificulta quem estiver começando e poderia contribuir com o código-fonte, mas um profissional que não seja fluente em Inglês, ainda consegue contribuir. É uma barreira pequena no começo, mas no longo prazo é fácil de seguir e 99% dos projetos estão em Inglês.

Concordo com o @lbssousa!

**Comment by farribeiro** [comment]
log de sistema, e demais warnings de debugger em inglês?

**Comment by edersoares** [comment]
Não foi pensado @farribeiro, mas a nível de log, acredito poder ser em inglês também, apenas mensagens para usuário em português, mas é algo a se discutir.

**Comment by Bonot** [comment]
Olá, deixando aqui minha contribuição para o assunto:

Acredito que encima da ferramenta do Laravel, por uma questão de padrão de linguagem, talvez fosse melhor o inglês mesmo. Mas acho que, se for usar o inglês como opção, o dicionário de termos (pelo menos termos do vocabulário usado na área de educação) deve ser desenvolvido antes de qualquer implementação, e não o contrário. Digo isso pois trabalhando no processo de trazer alguns relatórios para a comunidade tive dificuldades com nomenclaturas de procedimentos escolares.

**Comment by vicentimartins** [comment]
Olá pessoal.
Alguma definição sobre essa issue?
Segui o guia de contribuição e não vi nenhum ponto que aborde essa issue.

Algum outro canal em que eu possa me informar melhor?

**Comment by edersoares** [comment]
@vicentimartins estamos iniciando a definição de alguns termos chaves, logo iremos disponibilizar na comunidade para todos seguirem o padrão e entender o domínio.
