### ISSUE TITLE
Problema ao retornar situação anterior de Matrícula de aluno com transferência interna

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#48]
MENU:
i-Educar - Escola > Cadastros > Aluno > Alunos > acessar um aluno e visualizar suas matrículas

PROBLEMA:
Após cancelar uma matrícula de um aluno com a situação Em andamento na nova escola onde um aluno foi admitido por transferência interna (escola do sistema), ao cancelar esta matrícula, a matrícula anterior na escola origem está sendo considerando como uma transferência externa, pois ao visualizá-la, mostra a opção "Cancelar transferência (escola externa)".

SOLUÇÃO:
Para este caso, teríamos 02 possibilidades de soluções a apresentar:

1ª - Retornar a situação anterior da matrícula (na escola Origem), colocando em Em andamento e reativando a solicitação de transferência interna. Esse caso, seria inverso ao procedimento normal, retorno as situações origem.

OU

2ª - Caso a matrícula da escola destino tenha sido Cancelada, Manter a matrícula anterior (escola origem) como Transferido, e com data de saída informada, habilitando somente o botão Voltar ao consultar a matrícula. Não saberia informar prontamente qual situação uma Matrícula com situação Transferida habilitaria somente o botão Voltar, precisaríamos estudar as dependências no banco de dados e aplicação para isto. 

A priori, considere a primeira opção a mais conveniente, porém, é válido verificar junto as instituições se isto não atrapalha os procedimentos da escola origem, que terá de volta um aluno nas suas listagens e consultas com a situação em Andamento, sendo que já havia "transferido" de sua escola.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá,

optei por implementar a 1ª solução proposta. Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
