### ISSUE TITLE
Obrigar a utilizar dados de endereçamento normalizados (pré-cadastrados) no endereço de pessoas e alunos

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#50]
MENU:
Módulo Pessoa FJ

PROBLEMA:
Atualmente, o usuário é obrigado a informar um endereço de pessoa física, porém, pode utilizar um pré-cadastrado ou digitar diretamente na tela de cadastro da pessoa. Isso gera uma série de problemas, pois usuários que digitam os dados manualmente (e não usam do mód Endereçamento), cometem erros e não geramos informação normalizada, inviabilizando, por exemplo, emitir uma relação de pessoas/alunos de um determinado logradouro ou bairro.

Por experiência em treinamentos feitos pela prestadora de serviços Portabilis, já é recomendado que a Secretaria de Educação padronize os endereçamentos, e as unidades escolares USEM SEMPRE a lupa para buscar um pré-cadastrado e evitem de ficar digitando diretamente os dados (não normalizados) no cadastro da pessoa.

SOLUÇÃO:
Criar um parâmetro que possa ser configurado e obrigue o usuário a buscar um endereçamento usando a lupa, ou seja, os campos do endereço não poderão ser digitados diretamente na pessoa. Para resolução mais pontual, também podemos não criar este parâmetro, e padronizar a busca do endereço na lupa, que é o ideal e o que a maioria dos gestores devem pensar, a nível de organização de dados. Ou seja, seriam bloqueados para digitação os campos do endereço.

Verificar também o Comportamento da opção "[Cadastrar Novo Endereço]" disponível dentro da pop-up que busca os endereços. Talvez este link deva ser desativado, pois ao clicar nele, pode habilitar os campos para digitação novamente.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá,

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
