### ISSUE TITLE
Em Documentos, criar uma opção para exportar/imprimir carteira de estudante/transp Escolar.

### ISSUE THREAD

**Issue by DiegonCastro** [portabilis/ieducar#55]
Devido a implementação de módulos recentes, como transporte escolar e uso de fotos, seria muito interessante no menu Documentos (módulo escola) uma opção para imprimir carteira de estudantes e também uma carteira para transporte escolar.

**Comment by giustin** [comment]
Olá, @DiegonCastro !

Sua ideia e propostas são interessantes, mas como não houve voluntários até agora para desenvolver sua demanda, estou finalizando esta tarefa. 

Se você já implementou isto, lhe convido a participar da Comunidade i-Educar [1] e disponibilizar esta evolução para outros usuários. Na Wiki da Comunidade, temos instruções para quem desejar contribuir com desenvolvimento.

[1] https://softwarepublico.gov.br/social/i-educar

Cordialmente,

Tiago de Faveri Giusti
Coordenação da Comunidade i-Educar
