### ISSUE TITLE
Criar relatórios de alunos matriculados, e também que usam transporte escolar.

### ISSUE THREAD

**Issue by DiegonCastro** [portabilis/ieducar#56]
Disponibilizar no menu relatórios a opção de visualização de quantos alunos estão matriculados, e quantos destes utilizam transporte escolar. Isso é fundamental para planejamento de motoristas, frotas, remanejamento, etc.

Seria interessante utilizar gráficos, mas em números mesmo já seria de grande valor.

**Comment by giustin** [comment]
Olá, @DiegonCastro !

Sua ideia e proposta de relatórios são interessantes, mas como não houve voluntários até agora para desenvolver sua demanda, estou finalizando esta tarefa. Se você já implementou isto, lhe convido a participar da Comunidade i-Educar [1] e disponibilizar esta evolução para outros usuários.

[1] https://softwarepublico.gov.br/social/i-educar

Cordialmente,

Tiago de Faveri Giusti
Coordenação da Comunidade i-Educar
