### ISSUE TITLE
Criar um menu de ocorrências disciplinares

### ISSUE THREAD

**Issue by DiegonCastro** [portabilis/ieducar#57]
Criar um módulo onde tenha:

*Lançamentos/alterações/exclusões de ocorrências disciplinares.
*Relatórios de ocorrências disciplinares - Individual e por turma.

**Comment by giustin** [comment]
Olá, @DiegonCastro !

Sua ideia e propostas são interessantes, mas como não houve voluntários até agora para desenvolver sua demanda, estou finalizando esta tarefa. 

Se você já implementou isto, lhe convido a participar da Comunidade i-Educar [1] e disponibilizar esta evolução para outros usuários. Na Wiki da Comunidade, temos instruções para quem desejar contribuir com desenvolvimento.

[1] https://softwarepublico.gov.br/social/i-educar

Cordialmente,

Tiago de Faveri Giusti
Coordenação da Comunidade i-Educar
