### ISSUE TITLE
Implementar maneira de realizar empréstimos em lote para uma turma do i-Educar Escola

### ISSUE THREAD

**Issue by lucassch** [portabilis/ieducar#60]
MENU:
Movimentação > Empréstimos ou Empréstimos em Lote

PROBLEMA:
Atualmente, só é permitido efetuar empréstimos para um cliente da biblioteca, não sendo possível efetuar empréstimos em lotes para turmas de determinada escola.

SOLUÇÃO
Na interface de empréstimos, permitir selecionar a turma do i-Educar - Escola, e realizar empréstimos para todos os alunos de uma turma, em lote. Informando o tombo de cada exemplar que será emprestado, e gravar para a turma, não a um cliente. Neste caso, permitir filtrar por Escola, Curso e Série listando as turmas para que sejam selecionadas para o empréstimo em lote.
Deve ser possível selecionar

**Comment by giustin** [comment]
Olá, @lucassch !

Inicialmente esta tarefa estava planejada para o milestone dos alunos da UnB, mas como eles não tiveram tempo hábil para finalizar e não houve mais voluntários até agora, estou finalizando esta tarefa. 

Caso alguém tenha interesse em desenvolver esta tarefa, fica o convite para participar da Comunidade i-Educar [1] e disponibilizar esta evolução para outros usuários. Na Wiki da Comunidade, temos instruções para quem deseja contribuir com desenvolvimento.

[1] https://softwarepublico.gov.br/social/i-educar

Cordialmente,

Tiago de Faveri Giusti
Coordenação da Comunidade i-Educar
