### ISSUE TITLE
Remover campo 'Tombo automático' do cadastro de dados da biblioteca

### ISSUE THREAD

**Issue by lucassch** [portabilis/ieducar#61]
MENU:
i-Educar Biblioteca > Cadastros > Dados da Biblioteca

PROBLEMA:
Atualmente temos um campo neste cadastro, que diz respeito a geração de Tombo Automático e é desnecessário, pois o sistema já cadastra os exemplares com um Tombo automático quando cadastrado sem o Tombo.

SOLUÇÃO:
Remover o campo 'Tombo automático' do detalhe da biblioteca e do cadastro de dados da biblioteca.

**Comment by giustin** [comment]
Olá, @lucassch !

Inicialmente esta tarefa estava planejada para o milestone dos alunos da UnB, mas como eles não tiveram tempo hábil para finalizar e não houve mais voluntários até agora, estou finalizando.

Caso alguém tenha interesse em desenvolver esta tarefa, fica o convite para participar da Comunidade i-Educar [1] e disponibilizar esta evolução para outros usuários. Na Wiki da Comunidade, temos instruções para quem deseja contribuir com desenvolvimento.

[1] https://softwarepublico.gov.br/social/i-educar

Cordialmente,

Tiago de Faveri Giusti
Coordenação da Comunidade i-Educar
