### ISSUE TITLE
Melhorar listagem de exemplares

### ISSUE THREAD

**Issue by lucassch** [portabilis/ieducar#62]
MENU:
i-Educar Biblioteca > Cadastros > Exemplares

PROBLEMAS:
Não é possível buscar exemplares por motivos de baixa, autores e assuntos.
Também não são exibidos na listagem os tipos de baixas dos exemplares com baixa.

SOLUÇÃO:
* Criar campo de busca para tipo de baixa;
* Criar campo de busca estio simpleSearch para autores e assuntos;
* Adicionar coluna 'Tipo de baixa' na listagem. Quando o exemplar não tiver baixa deve ser exibido um traço '-';

**Comment by giustin** [comment]
Olá, @lucassch !

Inicialmente esta tarefa estava planejada para o milestone dos alunos da UnB, mas como eles não tiveram tempo hábil para finalizar e não houve mais voluntários até agora, estou finalizando.

Caso alguém tenha interesse em desenvolver esta tarefa, fica o convite para participar da Comunidade i-Educar [1] e disponibilizar esta evolução para outros usuários. Na Wiki da Comunidade, temos instruções para quem deseja contribuir com desenvolvimento.

[1] https://softwarepublico.gov.br/social/i-educar

Cordialmente,

Tiago de Faveri Giusti
Coordenação da Comunidade i-Educar
