### ISSUE TITLE
Permitir informar feriados sem ano no cadastro de Dados da Biblioteca

### ISSUE THREAD

**Issue by lucassch** [portabilis/ieducar#63]
MENU:
i-Educar Biblioteca > Cadastros > Dados da Biblioteca

PROBLEMA:
Usuários tem que cadastrar feriados todo ano, sendo que a maioria dos feriados tem data fixa para todos os anos.

SOLUÇÃO:
Modificar cadastro para que tenha alguma opção para 'Feriado permanente', onde não seja especificado campo ano.

**Comment by giustin** [comment]
Olá, @lucassch !

Inicialmente esta tarefa estava planejada para o milestone dos alunos da UnB, mas como eles não tiveram tempo hábil para finalizar e não houve mais voluntários até agora, estou finalizando.

Caso alguém tenha interesse em desenvolver esta tarefa, fica o convite para participar da Comunidade i-Educar [1] e disponibilizar esta evolução para outros usuários. Na Wiki da Comunidade, temos instruções para quem deseja contribuir com desenvolvimento.

[1] https://softwarepublico.gov.br/social/i-educar

Cordialmente,

Tiago de Faveri Giusti
Coordenação da Comunidade i-Educar
