### ISSUE TITLE
Erro na Exportação de Dados

### ISSUE THREAD

**Issue by ivenspontes** [portabilis/ieducar#770]
**MENU:**

Configurações > Ferramentas > Exportação de Dados

**DESCRIÇÃO:**

Erro ao tentar exportar dados

**OBSERVAÇÕES:**

A primeira causa do erro está relacionado ao driver do filesystem, onde ele tenta acessar o driver 'pgsql' que não existe, que vem da variável $sftp que recebe o nome da conexão do banco de dados. 
O segundo erro é quando o 'SAVE' DO postgres gera o arquivo csv na pasta /tmp/ que o filesystem do laravel não tem acesso.

Arquivo que gera o erro:

[DatabaseToCsvExporter.php](https://github.com/portabilis/i-educar/blob/e5a6c191cea8140638ba45e9caa199420140b686/app/Jobs/DatabaseToCsvExporter.php#L104)

**AMBIENTE:**

- Todos os ambientes

**Comment by edersoares** [comment]
O exportador funciona corretamente na estrutura atual, porém a estrutura é necessária que o banco de dados esteja em outro servidor com acesso SFTP configurado para que assim que o arquivo `.csv` gerado no servidor do banco de dados seja buscado e então enviado para o S3. 

Isso é necessário para uma abordagem escalável onde arquivos sejam armazenados em serviços especializados e o arquivo seja gerado no servidor de banco de dados com o intuito de aumentar a performance.

A comunidade pode desenvolver outro adaptador onde o processo seja mais simples e seja executado tudo em um servidor apenas (servidor de aplicação), processamento e armazenamento do arquivo gerado.

Isso é uma funcionalidade a ser desenvolvida.

**Comment by msoares94** [comment]
Olá @edersoares, essa configuração de SFTP fica armazenada no `.env` ? Pergunto pois vi no `.env` que tem o bloco destinado ao S3 da AWS mais não vi do SFTP.

Se sim, poderia informar as chaves que deve ser adicionadas ou orientar onde posso encontrar elas na aplicação? Pergunto, pois teoricamente de eu configurar o FTP na mesma máquina e habilitar ele localmente a funcionalidade teoricamente deveria funcionar certo ?

**Comment by edersoares** [comment]
@marcosoliveirasoares94 isso fica no filesystem do próprio Laravel https://laravel.com/docs/filesystem, então basta configurar de acordo.

O que acontece é que internamente o nome do driver de filesystem tem que ser igual da conexão do banco de dados (motivos de multi-tenant) e o exportador hoje trabalha pensando na arquitetura e no fluxo:

- Aplicação dispara job pra fazer exportação
- Job roda SQL no banco de dados para gerar arquivo CSV no servidor de banco de dados
- SFTP busca arquivo no servidor de banco de dados
- Envio é feito para S3
- URL do S3 é gerada e encaminhada para usuário

Eu sugiro que a melhor maneira é a comunidade criar um adaptador que desacople estas linhas do código a fim de simplificar o processo:

https://github.com/portabilis/i-educar/blob/e5a6c191cea8140638ba45e9caa199420140b686/app/Jobs/DatabaseToCsvExporter.php#L106-L135

**Comment by msoares94** [comment]
@edersoares, se a implantação dessa instância de banco de dados estivesse em um RDS na AWS a funcionalidade também apresentaria erro correto?

**Comment by edersoares** [comment]
Em um RDS sim, pois não há acesso via SFTP ao servidor.

**Comment by msoares94** [comment]
> Em um RDS sim, pois não há acesso via SFTP ao servidor.

Imaginei, mais não somente isso, como também tem funções no qual o ieducar utiliza que nem o usuário mestre `postgres` tem acesso no RDS.

**Comment by edersoares** [comment]
Atualmente não trabalhamos com RDS, então não sei dizer corretamente, mas acredito que o acesso é mais limitado por se tratar de PaaS.

**Comment by msoares94** [comment]
@ivenspontes, quando você conseguiu exportar os dados, como ficou a configuração do FTP no arquivo .env?

**Comment by msoares94** [comment]
> @ivenspontes, quando você conseguiu exportar os dados, como ficou a configuração do FTP no arquivo .env?

@edersoares, poderia informar como ficaria isso no .env em relação a configuração de conexão do psql ?

**Comment by edersoares** [comment]
No arquivo `config/filesystem.php` precisa existir um disco _disks_ com o mesmo nome da conexão do banco:

```php
    'disks' => [
        'local' => [],
        'public' => [],
        'minio' => [],
        's3' => [],
        // Adicionar as linhas abaixo
        'pgsql' => [
            'driver' => 'sftp',
            'host' => 'IP_SERVIDOR_BANCO_DE_DADOS',
            'username' => 'USER_SERVIDOR_BANCO_DE_DADOS',
            'root' => '/',
            'privateKey' => '/home/ubuntu/.ssh/id_rsa', // Essa chave tem que estar no servidor de aplicação e a .pub no servidor de banco de dados 
            'database' => 'NOME_BANCO_DE_DADOS',
        ],
    ],
```

**Comment by msoares94** [comment]
Obrigado pelo retorno @edersoares.

Agora entendi onde deve ser configurado, estava presumindo que era somente no arquivo .env.

Não seria interessante manter essa configuração do driver pgsql nesse arquivo? Se sim, podemos programar para o próximo PR.

Então se entendi bem, configurando desta forma, e configurando o vsftp certinho, gerando os pares de chaves a funcionalidade estaria funcionando 100%. Ai caso o administrador optasse por enviar o arquivo para o S3 da AWS só precisaria alterar a FILESYSTEM_DRIVER, para o disco correspondente.

Vou testar e volto aqui para dar o feedback!

**Comment by msoares94** [comment]
> Obrigado pelo retorno @edersoares.
> 
> Agora entendi onde deve ser configurado, estava presumindo que era somente no arquivo .env.
> 
> Não seria interessante manter essa configuração do driver pgsql nesse arquivo? Se sim, podemos programar para o próximo PR.
> 
> Então se entendi bem, configurando desta forma, e configurando o vsftp certinho, gerando os pares de chaves a funcionalidade estaria funcionando 100%. Ai caso o administrador optasse por enviar o arquivo para o S3 da AWS só precisaria alterar a FILESYSTEM_DRIVER, para o disco correspondente.
> 
> Vou testar e volto aqui para dar o feedback!

@edersoares, passando para informar que ocorreu tudo certo com a funcionalidade após realizar as devidas configurações. Tenho uma ressalva, após entender a codificação pensando no escalonamento, não seria mais interessante desacoplar tal processo da responsabilidade das funções do PostgreSQL e dessa forma poder usar um DB como serviço que já contrata o serviço com bkp e alta disponibilidade ?

Em relação a particularidade de instalações em um único servidor o ideal é desacoplar o trecho de código de realiza a conexão remota no servidor do banco de dados.
Acredito que pode ser criado uma variável de controle no .env e carregar ela numa tomada de decisão dentro de tal classe.
Se estiver de acordo, posso trabalhar nisso e realizar um PR.

Em relação ao `config/filesystems.php`, não seria interessante manter essa configuração do driver pgsql nesse arquivo?

**Comment by ivenspontes** [comment]
> > Obrigado pelo retorno @edersoares.
> > 
> > Agora entendi onde deve ser configurado, estava presumindo que era somente no arquivo .env.
> > 
> > Não seria interessante manter essa configuração do driver pgsql nesse arquivo? Se sim, podemos programar para o próximo PR.
> > 
> > Então se entendi bem, configurando desta forma, e configurando o vsftp certinho, gerando os pares de chaves a funcionalidade estaria funcionando 100%. Ai caso o administrador optasse por enviar o arquivo para o S3 da AWS só precisaria alterar a FILESYSTEM_DRIVER, para o disco correspondente.
> > 
> > Vou testar e volto aqui para dar o feedback!
> 
> @edersoares, passando para informar que ocorreu tudo certo com a funcionalidade após realizar as devidas configurações. Tenho uma ressalva, após entender a codificação pensando no escalonamento, não seria mais interessante desacoplar tal processo da responsabilidade das funções do PostgreSQL e dessa forma poder usar um DB como serviço que já contrata o serviço com bkp e alta disponibilidade ?
> 
> Em relação a particularidade de instalações em um único servidor o ideal é desacoplar o trecho de código de realiza a conexão remota no servidor do banco de dados.
> Acredito que pode ser criado uma variável de controle no .env e carregar ela numa tomada de decisão dentro de tal classe.
> Se estiver de acordo, posso trabalhar nisso e realizar um PR.
> 
> Em relação ao `config/filesystems.php`, não seria interessante manter essa configuração do driver pgsql nesse arquivo?
> 
> 

O que você mudou para ficar tudo certo localmente?

Para funcionar corretamente tive que jogar a responsabilidade para o php, já usando o SQL que vem do EXPORT.

**Comment by msoares94** [comment]
Olá @ivenspontes, no meu caso, funcionou todo corretamente seguindo a infraestrutura informada, tendo 4 instâncias, sendo 1 para o banco de dados do i-educar, 1 para o banco de dados do i-diário, 1 para o servidor de aplicação do ieducar e a outra com o servidor de aplicação do i-diário.


Mais como mencionei, acredito que funciona também configurando o vsftp na mesma máquina e criando as configurações como se fosse fazer uma conexão sftp remota, o lance que isso basicamente é uma conexão sftp do servidor para ele mesmo e por isso o @edersoares aconselha criar um fluxo separado para casos como esse de implantação do i-educar e banco de dados no mesmo servidor, pois a infraestrutura pensada esta correta.

Imagino que a Portabilis tenha basicamente isso na produção deles, ou algo um pouco mais diferente.

Por exemplo:

Ter várias instâncias do i-educar com nginx e php, usando um banco de dados REDIS para todas as instâncias e o mesmo servidor de banco de dados para todas as instâncias e separando os clientes por database, para atender a demanda deles com o conceito Multitenancy.

Eles devem conseguir tratar o trafego dos clientes com alguma ferramenta para direcionar a aplicação a abrir a conexão com o schema específico daquele cliente com base na URL de acesso.

Por isso falo que o fluxo de exportação está correto, pois dessa forma a funcionalidade exportaria somente os dados daquele cliente no qual foi solicitado.

**Comment by msoares94** [comment]
@ivenspontes, quero montar uma frente de pessoas da comunidade iEducar, para consolidar informações, deixando de forma mais organizada a documentação de implantação e utilização do sistema, estou recrutando pessoas voluntárias que estão dispostas a ajudar com as demandas.

Você não se interessa em participar ?

**Comment by msoares94** [comment]
@ivenspontes ou @edersoares 

Uma vez que isso não é um BUG da aplicação, algum de vocês poderia prosseguir com o fechamento da issue?
