### ISSUE TITLE
Tabela settings com informações erradas

### ISSUE THREAD

**Issue by msoares94** [portabilis/ieducar#777]
**MENU:**

Tabela public.settings

**DESCRIÇÃO:**

Ao realizar a instalação limpa da versão 2.6.3 a tabela public.settings, veio com informações erradas para as colunas type, description e setting_category_id

Por exemplo, todos os registros foram inseridos como string, e somente 2 registros tiveram o setting_category_id definido corretamente, todos os demais vieram com o valor 1

**OBSERVAÇÕES:**

Existi alguns PR que foram tratados e liberados na 2.6.2 no qual corrigia tais itens.

**AMBIENTE:**

- Plataforma utilizada (instalação direta)
- Sistema operacional e versão (Ubuntu 20.04)
- Outros detalhes importantes

**Comment by msoares94** [comment]
@edersoares

O erro acima foi causado devido a renomeação da migration de `database/migrations/2020_08_03_000000_populate_settings_table.php` para `database/migrations/2021_01_01_000000_populate_settings_table.php`

Fazendo com que a população ocorra após a execução das migrations abaixo que deveria ser executadas após a população da tabela settings:
`
database/migrations/2020_08_03_151235_populate_settings_categories_table.php
database/migrations/2020_08_03_165637_update_categories_in_settings.php
database/migrations/2020_08_03_170501_atualiza_nomenclatura_dos_campos_da_tela_de_configuracoes.php
database/migrations/2020_08_04_143226_atualiza_tipo_dos_campos_da_tela_de_configuracoes.php`


A renomeação da migration ocorreu no [PR 776](https://github.com/portabilis/i-educar/pull/776/files)

Podemos seguir de duas formas:

1° Voltamos com o nome antigo da migration (Dessa forma somente novas instalação estariam com o problema corrigido.)

2° Reordenamos as migrations citadas para serem executadas nas novas instalações e/ou atualizações de versões.

Aguardo sua consideração.

**Comment by edersoares** [comment]
@marcosoliveirasoares94 temos internamente uma migration que faz essa configuração pra nossa realidade e por isso foi renomeada, precisamos renomear as demais migrations para o comportamento ficar correto em todos os lados https://github.com/portabilis/i-educar/pull/783.

**Comment by msoares94** [comment]
Entendo @edersoares,, então você já fez todo o tratamento necessário no [PR-783](https://github.com/portabilis/i-educar/pull/783) certo ?

**Comment by edersoares** [comment]
@marcosoliveirasoares94 exato! Consegue validar também?

**Comment by msoares94** [comment]
> @marcosoliveirasoares94 exato! Consegue validar também?

Olá @edersoares, realizei os testes em uma instalação limpa e ainda existe um erro em relação a categorização das configurações de integração entre o i-Educar e i-Diário, pois as 4 configurações ficaram na sessão "Sem categoria" ao invés de terem ficado em "Integração entre i-Educar e i-Diário", irei avaliar e solicitar ajuste via PR.

**Comment by msoares94** [comment]
> @marcosoliveirasoares94 temos internamente uma migration que faz essa configuração pra nossa realidade e por isso foi renomeada, precisamos renomear as demais migrations para o comportamento ficar correto em todos os lados #783.

Fiquei confuso nesse caso, vocês já tinha essa migrations que popular a tabela settings e essa nova migrations faz a mesma coisa porém em uma outra execução devido a ordem das migrations ?

Ou basicamente vocês mudaram o nome das migrations para elas serem executadas novamente em instalações já existentes sem alterar as configurações já mapeadas ?

**Comment by edersoares** [comment]
A migration que cria a estrutura existia em outro repositório interno devido a uma confusão, não podemos usar a sua migration porque senão o banco tentaria criar novamente a tabela gerando um erro.
