### ISSUE TITLE
Boletins não exibem notas de recuperação quando notas de recuperações específicas são utilizadas

### ISSUE THREAD

**Issue by robson-alcantara** [portabilis/ieducar#782]
Boletins não exibem notas de recuperação quando notas de recuperações específicas são utilizadas

**MENU:**

Escola > Documentos >Boletim

**DESCRIÇÃO:**

Boletins não exibem notas de recuperação quando notas de recuperações específicas são utilizadas nas regras de avaliação.

**OBSERVAÇÕES:**

Para a recuperação por etapa padrão, a nota correta aparece. O problema é que a coluna 'nota_arredondada' não é atualizada para esse tipo de recuperação (conforme figura). Provável arquivo que faz essa tarefa é ieducar/modules/Avaliacao/Assets/Javascripts/Diario.js

**AMBIENTE:**

- Versão do ieducar: 2.6.0

![image](https://user-images.githubusercontent.com/20538912/131394110-2d5d0104-e332-4efc-a006-8524bd5ce586.png)

**Comment by Bonot** [comment]
Olá, @robson-alcantara, tudo bem?

Eu não sei se entendi corretamente a sua necessidade, você conseguiria me explicar melhor de que forma vocês usam a recuperação específica no iEducar? É para todas as etapas ou apenas em algumas etapas específicas?

No caso de usarem para todas as etapas, poderiam adequar para usar a recuperação paralela, penso que funcionaria da mesma forma.

Nós criamos um boletim genérico para que atenda a maior parte dos casos. Mas nada impede que novos boletins sejam criados para atender casos mais específicos, acesse nosso [Guia de contribuição](https://github.com/portabilis/i-educar/blob/2.6/contributing.md) para mais informações.

**Comment by robson-alcantara** [comment]
Olá @Bonot, tudo bem e com você?

É para todas as etapas, porém neste ano foi configurado como recuperações específicas e não há como alterar já que tem avaliações lançadas.

O boletim atual funciona com essas recuperações, o que não ocorre é a atualização da coluna 'media_arrendondada'

**Comment by edersoares** [comment]
@robson-alcantara isso exigiria uma modificação no boletim. Sinta-se a vontade para abrir um PR fazendo o ajuste :)

**Comment by edersoares** [comment]
Encerrando, qualquer necessidade pode reabrir a issue ;)
