### ISSUE TITLE
Configurações de SMTP realizadas na interface da aplicação sendo ignoradas.

### ISSUE THREAD

**Issue by msoares94** [portabilis/ieducar#787]
**MENU:**

**Início / Configurações / Configurações de sistema**

**DESCRIÇÃO:**

Ao alterar as configurações da sessão **"SMTP - Configuração para envio de E-mail"**, a aplicação ignora as informações e continua lendo do arquivo .env

**OBSERVAÇÕES:**

Após as alterações na interface da aplicação, reiniciar o processo do NGINX e PHP-FPM

**AMBIENTE:**

- Plataforma utilizada (Docker e Instalação Direta)
- Sistema operacional e versão (Ubuntu 20.04)

**_Quando informado a mesma configuração passada na interface da aplicação no arquivo .env, a aplicação funciona 100%_**

**Comment by edersoares** [comment]
@marcosoliveirasoares94 as configurações são legadas e utilizadas para envio de e-mail de erro para o administrador.

Envio de erro para o administrador:

```
legacy.app.mailer.smtp.from_email
legacy.app.mailer.smtp.auth
legacy.app.mailer.smtp.from_name
legacy.app.mailer.smtp.host
legacy.app.mailer.smtp.password
legacy.app.mailer.smtp.username
legacy.app.mailer.smtp.port
legacy.app.mailer.smtp.encryption
```

Configurações corretas para sobrescrever o arquivo https://github.com/portabilis/i-educar/blob/2.6/config/mail.php#L39-L43:

```
mail.mailers.smtp.host
mail.mailers.smtp.port
mail.mailers.smtp.encryption
mail.mailers.smtp.username
mail.mailers.smtp.password
```

Basicamente as configurações da tabela `settings` sobrescrevem todas as configurações do Laravel.

Apenas para alinhamento, nenhum PR com sobrescrita de configuração do Laravel será aceito, pois isso impacta em todas as instalações.

**Comment by msoares94** [comment]
@edersoares, não sei se entendi bem!

1° Pergunta
Atualmente, as configurações presentes na sessão  **SMTP - Configuração para envio de E-mail**, tratam as configurações legadas, ou seja essas informações serão utilizadas pela aplicação para enviar notificações por e-mail caso ocorra algum erro, certo?

2° Pergunta
Caso não configuradas na interface, a aplicação tenta usar os valores do .env ? E em caso de configuradas, a aplicação não deveria ignorar as informações do .env

3° Pergunta
Pelo que percebi, as configurações que começam com `mail.mailers` utilizam as mesmas variáveis usadas pelas configurações que começam com `legacy.app.mailer`, logo as informações contidas na tabela settings que são preenchidas pela interface deveria funcionar para o envio de e-mail em caso de erro em em caso de redefinição de senha, certo?

Pois o que deu a entender que devo configurar duas formas a aplicação, uma definindo as configurações na interface da aplicação e outro no .env

**Comment by edersoares** [comment]
> Atualmente, as configurações presentes na sessão SMTP - Configuração para envio de E-mail, tratam as configurações legadas, ou seja essas informações serão utilizadas pela aplicação para enviar notificações por e-mail caso ocorra algum erro, certo?

Sim

> Caso não configuradas na interface, a aplicação tenta usar os valores do .env ? 

Ela sempre busca do `.env` a interface não influencia em nada no envio de e-mails (exceto o envio de erros).

> E em caso de configuradas, a aplicação não deveria ignorar as informações do .env

Como disse, essas configuração não servem para o envio de e-mail.

> Pelo que percebi, as configurações que começam com mail.mailers utilizam as mesmas variáveis usadas pelas configurações que começam com legacy.app.mailer, logo as informações contidas na tabela settings que são preenchidas pela interface deveria funcionar para o envio de e-mail em caso de erro em em caso de redefinição de senha, certo?

Errado. As configurações via interface não modificam nenhuma credencial de envio de e-mail.

> Pois o que deu a entender que devo configurar duas formas a aplicação, uma definindo as configurações na interface da aplicação e outro no .env

Se configurar apenas no `.env`, o que é o correto de configurar um ambiente, irá funcionar, as configurações da interface **não servem** para este fim de envio de e-mail do sistema, servem apenas para envio de e-mail de erros.

**Comment by msoares94** [comment]
Considerando os esclarecimento acima citados pelo @edersoares, irei realizar o fechamento da issue, tendo em vista que não é um BUG.

Obs.: @edersoares, nesse caso poderíamos ajustar a label da sessão **"SMTP - Configuração para envio de E-mail"** para **"SMTP - Configuração para envio de E-mail de Erros"**, o que acha ?

**Comment by edersoares** [comment]
@marcosoliveirasoares94 eu avançaria na realidade para a remoção destas configurações.

Há muitas configurações presentes em https://github.com/portabilis/i-educar/blob/2.6/config/legacy.php que já não são mais utilizadas, porém nunca houve uma revisão geral para entender o que deve ser mantido ou não.

Acredito que isso seria mais assertivo, pois diversas configurações apenas geram confusão.

**Comment by msoares94** [comment]
> @marcosoliveirasoares94 eu avançaria na realidade para a remoção destas configurações.
> 
> Há muitas configurações presentes em https://github.com/portabilis/i-educar/blob/2.6/config/legacy.php que já não são mais utilizadas, porém nunca houve uma revisão geral para entender o que deve ser mantido ou não.
> 
> Acredito que isso seria mais assertivo, pois diversas configurações apenas geram confusão.

Perfeito @edersoares, infelizmente não consigo saber o que poderia ser descontinuado devido o meu pouco contato com a solução. Poderíamos seguir com uma issue nova relatando a necessidade de revisão dos itens presentes no legacy ?

Estou disponível para evoluir e ajudar o máximo que eu puder.

**Comment by msoares94** [comment]
@edersoares, hoje me deparei com uma nova situação.

Ao tentar usar a interface para definir as configurações da sessão **AWS - S3 Armazenamento**, notei que ela solicita 3 informações, porém no .env são solicitadas 4 informações.

Gostaria de saber se esse é mais um caso no qual o valor da interface não é levado em consideração ou se está faltando adicionar a propriedade `AWS_DEFAULT_REGION` na tela de configurações?

Outro ponto que gostaria de saber sobre como utilizar a funcionalidade de Configurações e o arquivo .env, ao meu entender, algumas configurações não tem como serem migradas do .env para o banco de dados devido ao Tenant pois estaria replicando configurações que geralmente são as mesmas em todos das databases, é o caso das propriedades do AWS S3 ? Se sim não seria interessando remover elas da tela de configurações do sistema ? Se não, como fica a questão do agrupamento dos arquivos por tenant no AWS S3, ele cria um diretório com o nome do tenant automaticamente ou preciso definir em algum outro parâmetro o nome do agrupamento ?

**Comment by edersoares** [comment]
@marcosoliveirasoares94 estas configurações são do Laravel:

https://github.com/laravel/laravel/blob/4f8a0f35fabd8603fb756122bf820719a259ac9b/.env.example#L39-L43

Não faz sentido estar nas configurações do sistema visto que é uma configuração de ambiente.

**Comment by msoares94** [comment]
> @marcosoliveirasoares94 estas configurações são do Laravel:
> 
> https://github.com/laravel/laravel/blob/4f8a0f35fabd8603fb756122bf820719a259ac9b/.env.example#L39-L43
> 
> Não faz sentido estar nas configurações do sistema visto que é uma configuração de ambiente.

@edersoares, então vem o outro ponto.

1) - Não seria interessante remover elas da tela de configurações do sistema ?

2) - Com a configuração unificada no .env e aplicada a todos os tenant, como fica a questão do agrupamento dos arquivos enviados para o S3 por tenant, da forma que estou testanto, ele coloca todos os arquivos de todos os tenant no mesmo bucket porém não cria nenhuma espécie de separado por diretório.

**Comment by edersoares** [comment]
O mesmo bucket armazena os dados de todos os tenants agrupados por pasta, funciona assim atualmente, depende apenas da configuração da conexão dos tenants (banco de dados).

**Comment by msoares94** [comment]
> O mesmo bucket armazena os dados de todos os tenants agrupados por pasta, funciona assim atualmente, depende apenas da configuração da conexão dos tenants (banco de dados).

Entendi @edersoares, olhando as configurações a única chave que poderia ser possível seria `prefix` mais ela é usada para o banco de dado.

Dentro objeto de conexão só existem as seguintes informações:
```

        'pgsql' => [
            'driver' => 'pgsql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'schema' => 'public',
            'sslmode' => 'prefer',
        ],
```

Deixei passar algo ? Caso não seja possível informar, não se preocupe que me viro procurando no código sem nenhum problema.

**Comment by edersoares** [comment]
Agora que vi aqui no código, hoje está em uma configuração diferente https://github.com/portabilis/i-educar/blob/2.6/ieducar/intranet/include/file_check.php#L37 deve ser algo que estava na configuração anterior `.ini`.

**Comment by msoares94** [comment]
> Agora que vi aqui no código, hoje está em uma configuração diferente https://github.com/portabilis/i-educar/blob/2.6/ieducar/intranet/include/file_check.php#L37 deve ser algo que estava na configuração anterior `.ini`.

Entendi @edersoares, ao meu ver poderia ser tratado em uma variável separada das propriedades de banco de dados. Mais também entendi que a propriedade `legacy.app.database.dbname` recebe o valor de `$config['database']`, logo, no modelo de Tenant de vocês, provavelmente criam-se os os bancos de dados com o database contendo nome do tenant.

O estranho que no meu caso tenho os seguintes valores no .env

```

DB_CONNECTION=pgsql

DB_HOST=postgres
DB_PORT=5432
DB_DATABASE=ieducar
DB_USERNAME=ieducar
DB_PASSWORD=ieducar

ESCOLA_MUNICIPIO1_DB_HOST=postgres_municipio_1
ESCOLA_MUNICIPIO1_DB_PORT=5432
ESCOLA_MUNICIPIO1_DB_DATABASE=ieducar_1
ESCOLA_MUNICIPIO1_DB_USERNAME=ieducar_1
ESCOLA_MUNICIPIO1_DB_PASSWORD=ieducar_1

ESCOLA_MUNICIPIO2_DB_HOST=postgres_municipio_2
ESCOLA_MUNICIPIO2_DB_PORT=5432
ESCOLA_MUNICIPIO2_DB_DATABASE=ieducar_2
ESCOLA_MUNICIPIO2_DB_USERNAME=ieducar_2
ESCOLA_MUNICIPIO2_DB_PASSWORD=ieducar_2
```

No meu arquivo database.php tenho as seguintes informações:
```


        'escola.municipio1' => [
            'driver' => 'pgsql',
            'url' => env('ESCOLA_MUNICIPIO1_DATABASE_URL'),
            'host' => env('ESCOLA_MUNICIPIO1_DB_HOST', '127.0.0.1'),
            'port' => env('ESCOLA_MUNICIPIO1_DB_PORT', '5432'),
            'database' => env('ESCOLA_MUNICIPIO1_DB_DATABASE', 'forge'),
            'username' => env('ESCOLA_MUNICIPIO1_DB_USERNAME', 'forge'),
            'password' => env('ESCOLA_MUNICIPIO1_DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'schema' => 'public',
            'sslmode' => 'prefer',
        ],

        'escola.municipio2' => [
            'driver' => 'pgsql',
            'url' => env('ESCOLA_MUNICIPIO2_DATABASE_URL'),
            'host' => env('ESCOLA_MUNICIPIO2_DB_HOST', '127.0.0.1'),
            'port' => env('ESCOLA_MUNICIPIO2_DB_PORT', '5432'),
            'database' => env('ESCOLA_MUNICIPIO2_DB_DATABASE', 'forge'),
            'username' => env('ESCOLA_MUNICIPIO2_DB_USERNAME', 'forge'),
            'password' => env('ESCOLA_MUNICIPIO2_DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'schema' => 'public',
            'sslmode' => 'prefer',
        ],
```

Porém no S3 não foi criado o separado, eu esperar algo tipo `ieducar_1` e `ieducar_2`, ficou somente `ieducar`, provavelmente pegando a informação do DB_DATABASE=ieducar, tendo em vista que a minha propriedade `legacy.app.database.dbname` nos bancos de dados estão com o valor igual à `********` que veio nas migrations. Mais pelo que entendi o bloco de código abaixo sobrescreveria essa informação uma vez que o tenant é um Middleware

Arquivo: ConnectTenantDatabase
```
    public function handle($request, Closure $next)
    {
        $connections = config('database.connections');

        $tenant = $this->getTenant($request);

        if (isset($connections[$tenant])) {
            DB::setDefaultConnection($tenant);
        }

        return $next($request);
    }
```

Arquivo: LoadSettings
```
    private function getDatabaseConfig()
    {
        $config = DB::connection()->getConfig();

        return [
            'legacy.app.database.hostname' => $config['host'],
            'legacy.app.database.port' => $config['port'],
            'legacy.app.database.dbname' => $config['database'],
            'legacy.app.database.username' => $config['username'],
            'legacy.app.database.password' => $config['password'],
        ];
    }
```

![image](https://user-images.githubusercontent.com/12193221/132541679-fcea2faa-d39c-4b09-91d5-810fa25d3dd1.png)

**Comment by msoares94** [comment]
> > Agora que vi aqui no código, hoje está em uma configuração diferente https://github.com/portabilis/i-educar/blob/2.6/ieducar/intranet/include/file_check.php#L37 deve ser algo que estava na configuração anterior `.ini`.
> 
> Entendi @edersoares, ao meu ver poderia ser tratado em uma variável separada das propriedades de banco de dados. Mais também entendi que a propriedade `legacy.app.database.dbname` recebe o valor de `$config['database']`, logo, no modelo de Tenant de vocês, provavelmente criam-se os os bancos de dados com o database contendo nome do tenant.
> 
> O estranho que no meu caso tenho os seguintes valores no .env
> 
> ```
> 
> DB_CONNECTION=pgsql
> 
> DB_HOST=postgres
> DB_PORT=5432
> DB_DATABASE=ieducar
> DB_USERNAME=ieducar
> DB_PASSWORD=ieducar
> 
> ESCOLA_MUNICIPIO1_DB_HOST=postgres_municipio_1
> ESCOLA_MUNICIPIO1_DB_PORT=5432
> ESCOLA_MUNICIPIO1_DB_DATABASE=ieducar_1
> ESCOLA_MUNICIPIO1_DB_USERNAME=ieducar_1
> ESCOLA_MUNICIPIO1_DB_PASSWORD=ieducar_1
> 
> ESCOLA_MUNICIPIO2_DB_HOST=postgres_municipio_2
> ESCOLA_MUNICIPIO2_DB_PORT=5432
> ESCOLA_MUNICIPIO2_DB_DATABASE=ieducar_2
> ESCOLA_MUNICIPIO2_DB_USERNAME=ieducar_2
> ESCOLA_MUNICIPIO2_DB_PASSWORD=ieducar_2
> ```
> 
> No meu arquivo database.php tenho as seguintes informações:
> 
> ```
> 
> 
>         'escola.municipio1' => [
>             'driver' => 'pgsql',
>             'url' => env('ESCOLA_MUNICIPIO1_DATABASE_URL'),
>             'host' => env('ESCOLA_MUNICIPIO1_DB_HOST', '127.0.0.1'),
>             'port' => env('ESCOLA_MUNICIPIO1_DB_PORT', '5432'),
>             'database' => env('ESCOLA_MUNICIPIO1_DB_DATABASE', 'forge'),
>             'username' => env('ESCOLA_MUNICIPIO1_DB_USERNAME', 'forge'),
>             'password' => env('ESCOLA_MUNICIPIO1_DB_PASSWORD', ''),
>             'charset' => 'utf8',
>             'prefix' => '',
>             'prefix_indexes' => true,
>             'schema' => 'public',
>             'sslmode' => 'prefer',
>         ],
> 
>         'escola.municipio2' => [
>             'driver' => 'pgsql',
>             'url' => env('ESCOLA_MUNICIPIO2_DATABASE_URL'),
>             'host' => env('ESCOLA_MUNICIPIO2_DB_HOST', '127.0.0.1'),
>             'port' => env('ESCOLA_MUNICIPIO2_DB_PORT', '5432'),
>             'database' => env('ESCOLA_MUNICIPIO2_DB_DATABASE', 'forge'),
>             'username' => env('ESCOLA_MUNICIPIO2_DB_USERNAME', 'forge'),
>             'password' => env('ESCOLA_MUNICIPIO2_DB_PASSWORD', ''),
>             'charset' => 'utf8',
>             'prefix' => '',
>             'prefix_indexes' => true,
>             'schema' => 'public',
>             'sslmode' => 'prefer',
>         ],
> ```
> 
> Porém no S3 não foi criado o separado, eu esperar algo tipo `ieducar_1` e `ieducar_2`, ficou somente `ieducar`, provavelmente pegando a informação do DB_DATABASE=ieducar, tendo em vista que a minha propriedade `legacy.app.database.dbname` nos bancos de dados estão com o valor igual à `********` que veio nas migrations. Mais pelo que entendi o bloco de código abaixo sobrescreveria essa informação uma vez que o tenant é um Middleware
> 
> Arquivo: ConnectTenantDatabase
> 
> ```
>     public function handle($request, Closure $next)
>     {
>         $connections = config('database.connections');
> 
>         $tenant = $this->getTenant($request);
> 
>         if (isset($connections[$tenant])) {
>             DB::setDefaultConnection($tenant);
>         }
> 
>         return $next($request);
>     }
> ```
> 
> Arquivo: LoadSettings
> 
> ```
>     private function getDatabaseConfig()
>     {
>         $config = DB::connection()->getConfig();
> 
>         return [
>             'legacy.app.database.hostname' => $config['host'],
>             'legacy.app.database.port' => $config['port'],
>             'legacy.app.database.dbname' => $config['database'],
>             'legacy.app.database.username' => $config['username'],
>             'legacy.app.database.password' => $config['password'],
>         ];
>     }
> ```
> 
> ![image](https://user-images.githubusercontent.com/12193221/132541679-fcea2faa-d39c-4b09-91d5-810fa25d3dd1.png)

@edersoares, pensei que era um bug até começar a debugar e entender o fluxo.

Minha confusão foi em achar que as seguintes linhas faziam a mesma coisa kkk, ou seja, definir o valor em`$config`:

```
        $config = DB::connection()->getConfig();

        Config::set($this->getConfig());
```

Sendo que os passos são:
```

        Config::set($settings); # Defini a variável $settings com os valores em `settings`  do banco de dados.

        Config::set($this->getConfig()); # Defini a variável leancy.code com os valores de $config vindo da tabela `pmieducar.configuracoes_gerais`

        Config::set($this->getDatabaseConfig()); # Sobrescreve as propriedades `legacy.app.database.*` definidas anteriormente pelo primeiro comando
```

Além disso tudo no meu ambiente de desenvolvimento, a variável que defini o nome do banco está tratando o tenant como `postgres_municipio_1` e `postgres_municipio_2` mais no meu ambiente de **Staging** não, rsrsrs.

Desculpa ai pela mancada! A aplicação está sem nenhum problema na parte de integração com S3 usando o Tenant.

Tudo bem para você se criarmos uma issue para remoção dos registros de banco de dados  para a tabela `settings` cujo as chaves são essas abaixo. Tendo em vista que o valor informado na tela de Configurações de Sistema não interfere no comportamento da aplicação.
```
legacy.app.aws.bucketname
legacy.app.aws.awsacesskey
legacy.app.aws.awssecretkey
```

**Comment by edersoares** [comment]
@marcosoliveirasoares94 sem problemas :) 

Claro, podemos trabalhar sim com a remoção de vários registros da tabela settings visando que vários dos que existem lá são configurações legadas que não fazem mais sentido. Só tem que ser garantido que nada está sendo utilizado no código.

**Comment by msoares94** [comment]
> @marcosoliveirasoares94 as configurações são legadas e utilizadas para envio de e-mail de erro para o administrador.
> 
> Envio de erro para o administrador:
> 
> ```
> legacy.app.mailer.smtp.from_email
> legacy.app.mailer.smtp.auth
> legacy.app.mailer.smtp.from_name
> legacy.app.mailer.smtp.host
> legacy.app.mailer.smtp.password
> legacy.app.mailer.smtp.username
> legacy.app.mailer.smtp.port
> legacy.app.mailer.smtp.encryption
> ```
> 
> Configurações corretas para sobrescrever o arquivo https://github.com/portabilis/i-educar/blob/2.6/config/mail.php#L39-L43:
> 
> ```
> mail.mailers.smtp.host
> mail.mailers.smtp.port
> mail.mailers.smtp.encryption
> mail.mailers.smtp.username
> mail.mailers.smtp.password
> ```
> 
> Basicamente as configurações da tabela `settings` sobrescrevem todas as configurações do Laravel.
> 
> Apenas para alinhamento, nenhum PR com sobrescrita de configuração do Laravel será aceito, pois isso impacta em todas as instalações.

@edersoares 

Reativando essa conversa pois estou prestes a fazer uma alteração nisso com base no meu entendimento.

Só para alinhar antes de fazer o PR.

1° - Manter a categoria de ID 13 `SMTP - Configuração para envio de E-mail` porém renomear ela para `SMTP - Envio de erro para o administrador` contendo as chaves:

legacy.app.mailer.smtp.from_email
legacy.app.mailer.smtp.auth
legacy.app.mailer.smtp.from_name
legacy.app.mailer.smtp.host
legacy.app.mailer.smtp.password
legacy.app.mailer.smtp.username
legacy.app.mailer.smtp.port
legacy.app.mailer.smtp.encryption

2° - Criar uma nova categoria `SMTP - Envio de e-mails` contendo as chaves

mail.mailers.smtp.host
mail.mailers.smtp.port
mail.mailers.smtp.encryption
mail.mailers.smtp.username
mail.mailers.smtp.password

3° - Remover as chaves abaixo e sua respectiva categoria `AWS - S3 Armazenamento`

legacy.app.aws.bucketname
legacy.app.aws.awsacesskey
legacy.app.aws.awssecretkey
