### ISSUE TITLE
Configurações Gerais com erro no campo URL do logo

### ISSUE THREAD

**Issue by msoares94** [portabilis/ieducar#788]
**MENU:**

Início / Configurações / Configurações gerais

**DESCRIÇÃO:**

Ao realizar uma instalação limpa da aplicação, o **brasão na tela de login** é apresentada perfeitamente, avaliando o caminho da mesma, é possível ver que ela é carregada da _**URL: http://localhost/intranet/imagens/brasao-republica.png**_

O problema ocorre ao acessar a tela de **Configurações Gerais** e **altere qualquer campo com exceção do URL do logo**, ou simplesmente acesse a tela e clique em SALVAR, esse simples ato fará com que a logo na tela inicial não seja mais apresentada pois a aplicação persiste no banco de dados a **URL com valor vazio.**

**AMBIENTE:**

- Plataforma utilizada (Docker e instalação direta)
- Sistema operacional e versão (Ubuntu 20.04)
- i-Educar, versão >= 2.6.0

**Comment by jrbarros** [comment]
@marcosoliveirasoares94 fiz a validação aqui e erro detalhado não esta apresentando. Vou fechar a issue e se o problema aparecer novamente reabrimos.
