### ISSUE TITLE
Erro ao editar vínculo do servidor a turma

### ISSUE THREAD

**Issue by marcio944** [portabilis/ieducar#790]
**MENU:**

Servidores -> Cadastros -> Servidores -> Vincular professor a turmas

**DESCRIÇÃO:**

Quando clico no botão Editar demora um tempo carregando e aparece o erro: 504 Gateway Time-out
![Captura de tela de 2021-09-06 15-18-02](https://user-images.githubusercontent.com/33971614/132252060-503f5925-d0e6-45a8-90dc-e28fa05ef911.png)
![Captura de tela de 2021-09-06 15-19-33](https://user-images.githubusercontent.com/33971614/132252071-89ab60bd-49f1-4997-9782-eeb2d78acb91.png)

**AMBIENTE:**

- Plataforma utilizada: EC2 AWS

- Sistema operacional e versão: Ubuntu 18.04
 
- Navegador e versão (Mozilla Firefox 91.0.2)

- i-Educar 2.6.5

**Comment by edersoares** [comment]
@marcio944 precisamos de mais informações, versão, plataforma, etc.. o que está descrito no template.

**Comment by marcio944** [comment]
Editei e coloquei as informações

**Comment by jrbarros** [comment]
Testado na versão mais recente e erro não foi apresentado. Vamos fechar a issue e caso apareça novamente, montamos o caso de uso para correção.
