### ISSUE TITLE
Boletim do professor eventualmente exibe situação incorreta

### ISSUE THREAD

**Issue by robson-alcantara** [portabilis/ieducar#796]
**MENU:**

Escola > Documentos > Boletins > Boletim do professor

**DESCRIÇÃO:**

Boletim do professor eventualmente exibe situação incorreta do aluno

**AMBIENTE:**

- i-Educar: 2.6.0

![image](https://user-images.githubusercontent.com/20538912/133136173-6e339fb2-91dc-4832-a595-ebe8cd005cd6.png)

![image](https://user-images.githubusercontent.com/20538912/133136369-8c45e8ff-06f7-4588-afcc-aad22dbf3343.png)

![image](https://user-images.githubusercontent.com/20538912/133136485-7d0dac78-53b6-4a80-ad2d-f2c40263d77d.png)

![image](https://user-images.githubusercontent.com/20538912/133136584-7f103308-7674-4411-a116-9d4badf07bbe.png)

**Comment by edersoares** [comment]
@robson-alcantara com as novas versões foi resolvido?

**Comment by edersoares** [comment]
Encerrando, qualquer necessidade pode reabrir a issue ;)
