### ISSUE TITLE
Histórico de aluno transferido

### ISSUE THREAD

**Issue by kesllan** [portabilis/ieducar#799]
**MENU**
>Lançamentos/Falltas e notas
>Processos/Históricos escolares
>Relatórios/Relatório de conferência de notas e faltas
>Documentos/Boletins/Boletim Escolar

Após transferir um aluno não é possível fazer lançamentos de faltas e notas, nem emitir histórico, nem boletim, nem relatórios do mesmo, pois o aluno transferido não aparece mais na relação de alunos da turma

**OBSERVAÇÕES**

Pra mim é um BUG pois deveria ser possível selecionar o aluno e mostrar o status de transferido. A emissão do histórico faz se necessária após a transferência do aluno, pois é o documento que o mesmo precisa para comprovar sua escolaridade e notas na nova escola.

**AMBIENTE**
Instalação direta
Ubuntu 20.04
i-educar v2.53
![01](https://user-images.githubusercontent.com/47616123/135141005-033dce1f-1d7b-4ddb-8a14-5b05e38f3032.PNG)
![02](https://user-images.githubusercontent.com/47616123/135141010-4a80781e-3e5c-454c-9384-479cbe70c4d2.PNG)
![03](https://user-images.githubusercontent.com/47616123/135141011-1215cf88-1c40-436e-b8ed-c22ec311b200.PNG)
![04](https://user-images.githubusercontent.com/47616123/135141013-34c8f60b-46b6-4f34-ab87-67a39539063e.PNG)
![05](https://user-images.githubusercontent.com/47616123/135141017-da8e1086-82f3-4d29-b699-58636d8018ee.PNG)

**Comment by msoares94** [comment]
Isso realmente é importante @kesllan. UP!

**Comment by msoares94** [comment]
@kesllan, nos parâmetros da Instituição, tem uma opção para marcar em caso de transferência de alunos, o i-Educar já realizar a emissão do histórico.

No entanto também acredito que essa issue seja um BUG, tendo em vista que a escola em certos momentos pode querer emitir os documentos desse aluno transferido.

@edersoares ou @portabiler teriam alguma consideração?

**Comment by tiagocamargo** [comment]
Entendo que é regra de negócio. Após transferência o aluno não faz mais parte da turma, portanto sistema não deveria apresentar mais o aluno em processos que são apenas para alunos matriculados. 

A emissão dos documentos necessários para a transferência devem ser emitidos antes de iniciar o processo.

**Comment by msoares94** [comment]
Legal @tiagocamargo, obrigado pelo retorno!

Então o que você ou @portabiler acha do seguinte:

Não permitir a parametrização dessa opação `Gerar histórico de transferência ao transferir matrícula?`, pois atualmente ela pode ser desmarcada e se não me engano vem desmarcada por padrão.

Pois dessa forma, ao transferir um aluno, o histórico já seria emitido!

Acrescentaria até uma validação antes de efetivar a atransferência, validação essa para verificar se as faltas e notas está lançadas até o presente momento da transferência.

Acredito que isso deixaria o software mais completo e menos propício a erros humanos.

**Comment by edersoares** [comment]
@marcosoliveirasoares94 essa parametrização existe porque os municípios tem necessidades e fluxos diferentes, por isso precisa existir. Mas eu entendo que talvez possa ser um parâmetro default.

**Comment by msoares94** [comment]
@edersoares, obrigado pelo retorno!

Bom, acredito que ele pode ser sim verdadeiro como default, pois como não é possível emitir documentação de aluno transferido, pelo menos diminuiria a possibilidade de erro humano.

E em casos de municípios com fluxos diferentes acredito que o parâmetro marcado como verdadeiro não seria um problema tendo em vista que ele poderia desmarcar e emitir com o fluxo distinto, o que não ocorre quando é o contrário, bom pelo menos foi isso que entendi.

**Comment by kesllan** [comment]
> Entendo que é regra de negócio. Após transferência o aluno não faz mais parte da turma, portanto sistema não deveria apresentar mais o aluno em processos que são apenas para alunos matriculados.
> 
> A emissão dos documentos necessários para a transferência devem ser emitidos antes de iniciar o processo.

Entendo! Porém no Estado de Minas Gerais por exemplo, antes de emitir o histórico é emitido a declaração de transferência.  Depois de conferido os dados lançados pro aluno, emite-se o histórico.

Creio q se fosse possível visualizar os alunos transferidos pelo menos na tela de lançamentos de notas e faltas pra possíveis correções de dados, seria bom.

Aqui acontece tbm de alguns professores demorarem um pouco pra lançarem as notas. Quando o aluno é transferido tem q cancelar a transferência pra eles fazerem os lançamentos.

**Comment by edersoares** [comment]
@kesllan é uma melhoria válida sim! Porém é necessário fazer tal implementação, fique a vontade em abrir um PR para fazermos o merge ;)

**Comment by edersoares** [comment]
Encerrando, qualquer necessidade pode reabrir a issue ;)
