### ISSUE TITLE
Adicionar Data entrada e saída para vinculo professor à turma 

### ISSUE THREAD

**Issue by kesllan** [portabilis/ieducar#800]
**CONTEXTO:**

Quando um professor contratado deixa uma turma e se contrata outro professor é preciso excluir o vínculo do professor da turma. Para fins de registro, me parece estranho excluir o vínculo, pois não restará nada no sistema mostrando que o professor trabalhou naquela turma.

**IMPLEMENTAÇÃO:**

Poderia ter uma opção igual tem na tela de alocação de servidor na tela de vínculo de professor a turma, que pode definir a data de entrada e a data de saída. Assim não seria necessário excluir e poderemos saber q o professor lecionou naquela turma.

**Comment by edersoares** [comment]
Essa sugestão foi adicionada ao nosso roadmap, mas sem prazo para execução, se a comunidade desejar seguir com o desenvolvimento, podem reabrir a issue.
