### ISSUE TITLE
como integrar o i-educar com moodle

### ISSUE THREAD

**Issue by ghost** [portabilis/ieducar#804]
fala aí pessoal, espero que todos estejam bem.
seguinte, quero integrar o moodle com o sistema i-educar.
por acaso já há algo neste sentido.
quero fazer uma escola de cursos. então vou precisar de um sistema de gestão
sabem me informar se o i-educar possui sistema de gerenciamento de mensalidades?

grato desde já!

**Comment by rodrigocabral** [comment]
Olá @thadeu220, tudo bem com você?

O i-Educar não possui módulo financeiro. Ele foi feito para escolas públicas.

Mas nada impede de que alguém possa desenvolver.

Se quiser conhecer mais sobre o i-Educar, você pode acessar o https://forum.ieducar.org/.

Também existe um canal do [Telegram](https://t.me/ieducar).
