### ISSUE TITLE
como instalar o i-educar em servidor de hospedagem

### ISSUE THREAD

**Issue by ghost** [portabilis/ieducar#806]
fala aí pessoal, tudo bem
seguinte, eu fiz o download do pacote da última release do ieducar e movi os arquivos extraídos para o meu servidor, na pasta public_html.
e quando eu abro o meu software i-educar, me aparece o index of /sistema, com os arquivos do laravel, e os demais arquivos.
por que não está abrindo o instalador web.
eu rodei composer install mas, ele dá um erro de dependência antiga no package.json.

acredito que o material de instalação não segue os padrões necessários, ou estou cometendo um erro.

já executei vários softwares no meu servidor e não entendi ainda o por que o sistema não é inicializado, e me mostra as pastas, e aparentemente, não há um arquivo index.php

o que pode estar acontecendo?

ou eu devo forçar meu apache para olhar um outro diretório por padrão por simlink?

ajuda!

**Comment by edersoares** [comment]
@thadeu220 o i-Educar é um software complexo, então hospedagem compartilhada não funciona devido a inúmeras limitações impostas por questões de segurança. Sugiro utilizar uma VPS para fazer a instalação do mesmo.

A pasta pública que deve ser exposta para a internet é a `public`.

O i-Educar roda em cima do Laravel, então é basicamente fazer uma instalação Laravel em um servidor.

**Comment by jrbarros** [comment]
@thadeu220 estou fechando a issue por entender que sua duvida foi sanada.
