### ISSUE TITLE
Revisão de avaliação técnica

### ISSUE THREAD

**Issue by pamelazoe** [portabilis/ieducar#812]
## Issue de revisão de avaliação técnica:

Depois de comparar as informações apresentadas no repo oficial com os campos solicitados no modelo README.md, encontramos os seguintes pontos para melhorar:

- [x] Adicione o microsserviço de relatórios de avaliação estática do código Sonarcloud, tendo em mente que as condições ideais de relatório são:

      1 Ausência de falhas estruturais
      2 Menos de 25% de linhas duplicadas
      3 Menos de 10 problemas críticos
      4 Mais de 50% das classes, interfaces e métodos documentados
      5 Dívida técnica inferior a 30 dias
      6 Cobertura de teste de mais de 25%
      
      Isso é validado automaticamente quando você executa o relatório do último commit do repositório.
      
- [ ] Adicione o emblema na marcação deste serviço visível no readme.md.

**Comment by bid-code4dev** [comment]
@edersoares deixe-nos saber todas as perguntas sobre este issue de revisão. trabalhe no seu tempo, pois sabemos que estamos em datas de férias. Eles nos avisam e estamos vendo isso de forma assíncrona.

**Comment by edersoares** [comment]
@pamelazoe @knlopenknowledge foi dado seguimento e adicionado a análise do SonarCloud, segue https://sonarcloud.io/project/overview?id=portabilis_i-educar.
