### ISSUE TITLE
Correção de cores no calendário letivo

### ISSUE THREAD

**Issue by netocx** [portabilis/ieducar#815]
MENU:

Escola -> Cadastro -> Calendários

DESCRIÇÃO:

A legenda indica que dias letivos terão a cor azul, mas os dias não letivos aparecem na mesma cor

OBSERVAÇÕES:

O erro está no arquivo /ieducar/intranet/educar_calendario_ano_letivo_lst.php na linha 281

$obj_calendario->adicionarLegenda('Não Letivo', **'#VERDE_ESCURO'**);

AMBIENTE:

Plataforma utilizada: instalação direta
Sistema operacional e versão: Ubuntu 20.04
Navegador e versão: Chrome 96.0.4664.110
Outros detalhes importantes: i-Educar 2.6.7

**Comment by jrbarros** [comment]
Olá @netocx, muito obrigado pela contribuição.

Como já esta apontado o local exato da correção, você de se importaria de enviar um pull request com a correção? Ficaria muito feliz de analisar sua contribuição.

**Comment by jrbarros** [comment]
Issue resolvida em https://github.com/portabilis/i-educar/pull/823 novamente, muito obrigado!

**Comment by kesllan** [comment]
Só pra constar. Esse erro persiste na versão 2.6.8 . A solução apresentada aqui não resolveu.
