### ISSUE TITLE
Dicas

### ISSUE THREAD

**Issue by robertfsousa** [portabilis/ieducar#824]
O projeto é muito lindo e organizado.

Recomendo o uso:
- **Modular**: dividir o projeto em módulos, que podem ser exportados para outros projetos.
- **Webpackmix**: poderoso gerenciador dos recursos. Nele eu consigo importar somente uma parte das bibliotecas a serem usadas, minimizar, mesclar, versionamento e o melhor visualizar em tempo real nos navegadores as modificações, em diferentes tamanhos de telas.
- **FormRequest**: uma classe específica para a validação, deixando o controller mais limpo.
- Mudar o campo text de notifications para json. Assim terá a possibilidade de personalizar melhor as notificações, com partes em negritos.
- vi que algumas partes do código está em português. Eu me acostumei a escrever tudo em inglês, e foi minha primeira experiência com códigos em português.
- gosto de usar o **laratrust** para controle de acesso. Ele é ótimo, pois da para usar permissões para usuários, para os acessos (usuario x tenant) e para os tenant.

**Comment by jrbarros** [comment]
@robertfsousa muito obrigado pelo elogio ao projeto, sobre as recomendações de uso, posso adicionar algumas informações / questionamentos afim de buscar uma boa solução, vamos lá: 

> Modular: dividir o projeto em módulos, que podem ser exportados para outros projetos.

- Quais partes podemos dividir e como isso pode ajudar outros projetos ? 

> Webpackmix: poderoso gerenciador dos recursos. Nele eu consigo importar somente uma parte das bibliotecas a serem usadas, minimizar, mesclar, versionamento e o melhor visualizar em tempo real nos navegadores as modificações, em diferentes tamanhos de telas.
- Já tentei fazer isso, mas, não obtive sucesso, a ordem de carregamento e a utilização excessiva do `important` acabam desconfigurando ou não carregando adequadamente as paginas. A maneira de carregamento de assests do projeto foi desenhada em uma época onde não existia frameworks populares PHP muito menos JS,  com isso o alto acoplamento do PHP + HTML + JS era o padrão na época isso torna a melhoria proposta inviável no momento. Hoje e tem algumas partes já usando `blade` e continuamente estamos melhorando a abordagem de separação de tecnologias de BACK e FRONT, dai sim vamos poder utilizar ferramentas mais modernas no desenvolvimento. 

> FormRequest: uma classe específica para a validação, deixando o controller mais limpo.
- Temos varias implementações dessa técnica, ao poucos vamos melhorando o projeto gradativamente. 

> Mudar o campo text de notifications para json. Assim terá a possibilidade de personalizar melhor as notificações, com partes em negritos.
- É uma boa ideia, o trabalho maior e refatorar os lugares que usam isso para não quebrar a compatibilidade e criar uma layout do json para não colocar qualquer coisa. Consegue nos enviar um PR dessa sugestão? 

> vi que algumas partes do código está em português. Eu me acostumei a escrever tudo em inglês, e foi minha primeira experiência com códigos em português.
- O projeto é bem antigo, hoje mantemos um padrão para que novas implementações possam ser escritas em inglês. 

> gosto de usar o laratrust para controle de acesso. Ele é ótimo, pois da para usar permissões para usuários, para os acessos (usuario x tenant) e para os tenant.
- Não conhecia o **laratrust**, vou buscar mais informações sobre essa biblioteca.

Novamente, muito obrigado pelas dicas, fique a vontade de enviar um PR para o projeto, ficaria muito feliz em analisar sua proposta. 😄
