### ISSUE TITLE
Remover botões de cadastro rápido de novas séries e tipos de turmas no cadastro de turmas

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#83]
MENU:
i-Educar Escola > Cadastros > Turmas > Cadastrar

PROBLEMA:
Existem botões de cadastro rápido localizados ao lados dos campos Série e "Tipo de Turma", exibidos no momento que se inicia o cadastro de uma nova turma. Estes botões não estão funcionando.

SOLUÇÃO:
- [ ] Remover os botões de atalho para cadastro rápido, pois além de não estarem funcionando, é prudente que Séries e Tipos de turmas sejam cadastradas por pessoas com permissão específica, tendo em vista que são cadastrados mais estratégicos de configuração do sistema.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá,

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
