### ISSUE TITLE
404 no socket.io -> localhost:8080/socket.io/?EIO=3&transport=polling&t=O0UVzS8

### ISSUE THREAD

**Issue by alan-cleveston** [portabilis/ieducar#835]
**MENU:**
Em todas as telas, logo após o login, ao abrir o inspect do navegador google chrome v100 ele fica estourando o erro de acesso a essa url:

GET localhost:8080/socket.io/?EIO=3&transport=polling&t=O0UVzS8  > 404

**DESCRIÇÃO:**

Seria algum problema na configuração do NGINX no qual não encontra este socket.io? É possível solucionar utilizando um .htaccess?

**OBSERVAÇÕES:**

Nada deixa de funcionar, aparentemente, mas como sou novato, fico preocupado deste erro gerar maiores problemas.

**AMBIENTE:**

- Plataforma utilizada (Docker, instalação direta): Docker e instalação manual
- Sistema operacional e versão (Ubuntu 16.04, Windows 7): Arch Linux e Ubuntu
- Navegador e versão (Chrome 75): Google Chrome V100
- Outros detalhes importantes

**Comment by edersoares** [comment]
@alan-cleveston mude este linha https://github.com/portabilis/i-educar/blob/2.6/.env.example#L28 para:

```
BROADCAST_DRIVER=null
```

**Comment by alan-cleveston** [comment]
Deu certo, parou de estourar erro após alterar essa linha.
