### ISSUE TITLE
Erro ao definir novo ano letivo

### ISSUE THREAD

**Issue by alan-cleveston** [portabilis/ieducar#837]
**MENU:**
Escola -> Escolas -> Selecione uma escola -> Definir Ano Letivo.  
/intranet/educar_ano_letivo_modulo_cad.php

**DESCRIÇÃO:**

O erro acontece quando vai definir um novo ano letivo para qualquer escola, ao definir o ano e as etapas do ano letivo quando vai salvar gera esse erro que deixei no print.

**OBSERVAÇÕES:**

Estou utilizando a versão 2.6.8 clonada daqui do repositório.

**AMBIENTE:**

- Plataforma utilizada (Docker, instalação direta): Docker e instalação manual
- Sistema operacional e versão (Ubuntu 16.04, Windows 7): Arch Linux e Ubuntu
- Navegador e versão (Chrome 75): Google Chrome V100
- Outros detalhes importantes

Anexo print do erro:

![Erro ao definir ano letivo](https://user-images.githubusercontent.com/82655156/163682977-82df7674-c7d4-43a7-b26a-da6978c4da53.png)

**Comment by edersoares** [comment]
Veja se existe algum erro em `storage/logs`. Apague todos os arquivos lá, antes de executar a ação, execute e retorne o resultado.
