### ISSUE TITLE
Não está sendo possível conceder permissão aos menus pessoa física e pessoa jurídica para um mesmo usuário

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#84]
MENU:
DRH > Cadastro de Funcionários

PROBLEMA:
Ao acessar um usuário no cadastro de funcionários e ceder as permissões as funcionalidades "Pessoa física" e "Pessoa jurídica", percebe-se que apenas uma destas permissões é gravada, ou seja, não é possível ceder as duas permissões para um usuário.

SOLUÇÃO:
- [ ] Aplicar correção na funcionalidade de permissões para que seja possível atribuir acesso a ambas as funcionalidades para um mesmo usuário do sistema.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá,

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
