### ISSUE TITLE
Edição de usuário pelo módulo administrativo gera erro e exclui as permissões atuais

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#85]
MENU:
i-Educar Escola > Apresentação > Administrativo > Usuários

PROBLEMA:
Ao editar um usuário através do menu citado e alterar as informações, é apresentado uma mensagem de erro e as permissões dos usuários são apagadas.

SOLUÇÃO:
- [x] Aplicar correção na funcionalidade de permissões concedidas pelo menu Administrativo no mód. i-Educar - Escolar para que não exclua as permissões já existentes do usuário.

OBSERVAÇÕES:
Solução temporária: Atualmente, é possível fazer as alterações, excluindo todas as permissões do usuário através do módulo DRH.

**Comment by lucassch** [comment]
Olá,

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
