### ISSUE TITLE
Corrigir mensagem de confirmação exibida ao usuário ao excluir histórico escolares processados

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#86]
MENU:
i-Educar - Escolar > Movimentação > Processos > Histórico Escolar

PROBLEMA:
Ao tentar remover um histórico escolar já processado, deveria ser exibido ao usuário a mensagem "Confirma remoção dos históricos selecionados?", porém, conforme imagem a seguir, está sendo exibida uma mensagem com caracteres estranhos.
![image](https://cloud.githubusercontent.com/assets/1082624/6548834/dbc02e7c-c5e4-11e4-917e-0438c8743dde.png)

SOLUÇÃO:
- [ ] Corrigir a mensagem de confirmação exibida ao usuário quando tentar excluir um histórico escolar, na funcionalidade de processamento de históricos.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá,

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
