### ISSUE TITLE
Campo Carga Horária só armazena inteiro

### ISSUE THREAD

**Issue by kesllan** [portabilis/ieducar#867]
**DESCRIÇÃO:**
Percebi que alguns campos de carga horária do sistema só recebem os dados inteiros o que acaba causando um problema para algumas escolas que têm carga horária compostas de números fracionados. Por exemplo: A disciplina de Português aqui na nossa região é composta de 166 horas e 20 minutos. O sistema armazena só as 166 horas já que só aceita números inteiros. Sendo assim não é possível armazenar os minutos que deveriam ser registrados como 166.20

ieducar 2.6.0 a 2.7.4

**Comment by edersoares** [comment]
@kesllan atualmente esta é uma limitação devido ao elevado número de relatórios, você conseguiu evoluir com algo a este respeito?

**Comment by edersoares** [comment]
@kesllan estamos trabalhando em melhorar esta parte do sistema, já há na versão 2.8 que ainda não foi finalizada a carga horária fracionada. Pull request https://github.com/portabilis/i-educar/commit/abc96d25b474d2563bd2f3cafb3229ee4aafed5c
