### ISSUE TITLE
Não está sendo possível cadastrar reserva de exemplares no mód. biblioteca

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#87]
MENU:
i-Educar - Biblioteca > Cadastros > Reserva

PROBLEMA:
Ao tentar efetuar uma reserva, quando é selecionado o exemplar, emite a seguinte mensagem: “Situação atual do exemplar não permite reserva”. Verificado no cadastro do exemplar, e a situação estava setada corretamente, porém no cadastro de situação do exemplar existem dois campos que não estão gravando quando marcados, talvez possa ser estes campos que estejam impedindo a reserva

SOLUÇÃO:
- [ ] Alterar para que seja possível cadastrar reserva de exemplares no mód. Biblioteca.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá,

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
