### ISSUE TITLE
Dockerfile PHP

### ISSUE THREAD

**Issue by evertonvps** [portabilis/ieducar#871]
A url da https://github.com/portabilis/i-educar/blob/2.8/docker/php/Dockerfile#L42 esta retornando 404.. 
Correção: Substituir por http://dl-3.alpinelinux.org/alpine/v3.4/main

**Comment by edersoares** [comment]
@evertonvps você consegue validar se a branch https://github.com/portabilis/i-educar/tree/docker resolve o problema?

**Comment by msoares94** [comment]
@evertonvps e @edersoares, segue minha contribuição em relação a essa issue: https://github.com/portabilis/i-educar/pull/883

**Comment by edersoares** [comment]
Resolvido na branch https://github.com/portabilis/i-educar/tree/2.8.
