### ISSUE TITLE
Erro após instalação via Docker

### ISSUE THREAD

**Issue by JoaoPedro-Medeiros** [portabilis/ieducar#872]
**MENU:**

Não identificado

**DESCRIÇÃO:**

Estou a alguns dias tentando instalar a versão 2.7.4 do i-educar em minha máquina, porém o software apresenta o mesmo problema sempre que repito o processo de instalação via Docker. Primeiramente, durante a instalação, após a execução do "git clone https://github.com/portabilis/i-educar.git && cd i-educar", executo "docker-compose up -d --build" e logo após "docker-compose port nginx 80". Assim como nas imagens anexadas, acontece um erro durante a execução do comando "yarn install", porém ao fim do processo, o comando "docker-compose port nginx 80" é executado normalmente e mostra um resultado. Assim que coloco o endereço informado no navegador, a segunda imagem é mostrada, não me permitindo acesso ao link de nenhuma forma.

**OBSERVAÇÕES:**

O endereço, colocado como "http://0.0.0.0:49158" ou "http://localhost:49158", não funcionam da mesma forma. Além disso, ambos encaminham para a "http://<endereço>:49158/web" igualmente, onde a segunda imagem aparece.

**AMBIENTE:**

- Plataforma utilizada: Docker
- Sistema operacional e versão: Ubuntu 22.04
- Navegador e versão: Google Chrome Versão 107.0.5304.87 (Versão oficial) 64 bits

**Comment by JoaoPedro-Medeiros** [comment]
![photo_2022-11-01_13-50-07](https://user-images.githubusercontent.com/86727209/199604290-006bb60e-75c3-470c-9895-f96f8c520a58.jpg)
![photo_2022-11-01_13-51-05](https://user-images.githubusercontent.com/86727209/199604335-c030102e-199b-4f8c-bcff-f81485c46274.jpg)

**Comment by mazinhorj** [comment]
Aguardo solução também. Mesmo erro ocorre com a versão 2.8

Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy

**Comment by msoares94** [comment]
@JoaoPedro-Medeiros e @mazinhorj vocês podem modificar o Dockerfile da imagem php para isntalar o `yarn`, esse erro é ocasaionado pois o alias `new-install` chama outro alias `npm` como pode ser observado no `composer.json`.

Favor realizar a orientação e voltar aqui para comentar se deu certo a resolução do erro e fechar a issue se for o caso.
