### ISSUE TITLE
Erro ao tentar cadastrar pessoa física

### ISSUE THREAD

**Issue by NathanaelSantos** [portabilis/ieducar#877]
Olá e obrigado por nos ajudar a tornar o i-Educar um projeto mais estável. Não esqueça de revisar o nosso
[guia de contribuição](https://github.com/portabilis/i-educar/blob/master/CONTRIBUTING.md) para saber melhor como colaborar com a nossa comunidade. Para reportar seu bug use o template abaixo:

**MENU:**

``Pessoas -> Cadastros -> Pessoas Físicas``

**DESCRIÇÃO:**
Quando tento registar uma pessoa, recebo o erro descrito abaixo.

Fiz o processo descrito em: https://github.com/portabilis/i-educar#instala%C3%A7%C3%A3o-utilizando-docker no Fedora 37 e funcionou perfeitamente. No entanto, quando repeti o processo no Windows 11, e tentei registar uma pessoa, recebi o problema mostrado abaixo:

``UnexpectedValueException``

``The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/ieducar/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: Class "clsPermissoes" not found Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}}``

**-Recebi outro erro quando tentei rodar no Windows:**

`` ...  2022_05_30_171139_insert_educacenso_curso_superior ..................................................................................... 94ms DONE
  2022_05_31_172630_alter_record60_view_to_2022 ......................................................................................... 115ms DONE
  2022_05_31_190142_fix_migration_populate_posgraduate ................................................................................... 55ms DONE
  2022_06_06_093529_alter_table_settings_enable_educacenso_export ........................................................................ 13ms DONE
  2022_06_20_160118_alter_record20_view_fix_disciplines_with_teacher ..................................................................... 94ms DONE
  2022_06_22_105512_edit_view_person_add_religion_field ................................................................................. 467ms DONE
  2022_06_29_133818_update_cities ....................................................................................................... 297ms DONE
  2022_06_30_12345_create_view_student_grouped_registration ............................................................................. 101ms DONE
  2022_07_06_102852_change_orgao_regional_column_type ................................................................................... 113ms DONE

   INFO  Seeding database.  

  Database\Seeders\CountriesTableSeeder .................................................................................................... RUNNING  
  Database\Seeders\CountriesTableSeeder ........................................................................................... 2,573.40 ms DONE  

  Database\Seeders\StatesTableSeeder ....................................................................................................... RUNNING  
  Database\Seeders\StatesTableSeeder ................................................................................................ 262.53 ms DONE  

  Database\Seeders\CitiesTableSeeder ....................................................................................................... RUNNING  
  Database\Seeders\CitiesTableSeeder ............................................................................................. 45,556.15 ms DONE  

  Database\Seeders\DistrictsTableSeeder .................................................................................................... RUNNING  
  Database\Seeders\DistrictsTableSeeder .......................................................................................... 85,227.88 ms DONE  

Could not scan for classes inside "/var/www/ieducar/vendor/php-cs-fixer/diff/src/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/ieducar/vendor/php-cs-fixer/diff/src/" which does not appear to be a file nor a folder
> yarn install
sh: yarn: not found
Script yarn install handling the npm event returned with error code 127
Script @npm was called via new-install``

**OBSERVAÇÕES:**

Observações em geral sobre o problema apontado.

**AMBIENTE:**

- Plataforma utilizada (Docker, instalação direta)
``Docker``
- Sistema operacional e versão (Ubuntu 16.04, Windows 7)
  ``Edition	Windows 11 Home Single Language``
   ``Version	21H2``
  ``Installed on	‎26/‎07/‎2022``
 ``OS build	22000.1219``
  ``Experience	Windows Feature Experience Pack 1000.22000.1219.0``

- Navegador e versão (Chrome 75)
 ``Chrome``
  `Versão 107.0.5304.122 (Versão oficial) 64 bits`

- Outros detalhes importantes
``Warning: require(/var/www/ieducar/public/../vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/ieducar/public/index.php on line 34``

   ``Fatal error: Uncaught Error: Failed opening required '/var/www/ieducar/public/../vendor/autoload.php' 
   (include_path='.:/usr/local/lib/php') in /var/www/ieducar/public/index.php:34 Stack trace: #0 {main} thrown in 
   /var/www/ieducar/public/index.php on line 34``

**Comment by msoares94** [comment]
Olá @NathanaelSantos, esse seu problema não está relacionado a um erro do sistema.
Geralmente é uma instalação que ainda falta realizar algum passo a depender do SO que esteja utilizando.

Procura alguma solução aqui nesse fórum, mais acho que para windows não tem muita opção: https://forum.ieducar.org/

Ou pode na internet sobre o erro de `Permission denied para o Laravel no Windows` acredito que tenha alguma configuração a ser feita no seu SO.

**Comment by edersoares** [comment]
@NathanaelSantos conseguiu evoluir no seu problema? Atualmente temos enfrentando dificuldades com Docker e Windows, internamente usamos apenas sistemas Unix.

**Comment by edersoares** [comment]
Encerrando, qualquer necessidade pode reabrir a issue ;)
