### ISSUE TITLE
Criar funcionalidade para transferir notas e faltas juntamente com o aluno no processo de transferência

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#88]
MENU:
i-Educar - Escola > Cadastro > Aluno > Alunos

PROBLEMA:
Atualmente, tanto o usuário da escola que transferiu o aluno quanto o usuário da escola que está recebendo um aluno de transferência, não conseguem mais visualizar as notas da matrícula transferida. 

Isto é um problema, principalmente na escola que está recebendo o aluno, pois acaba sendo necessário redigitar todas as informações do boletim parcial, se ocorrer por exemplo, do aluno ser transferido para cursar a última etapa em outra escola da rede. Além disso, sem estas informações de notas e faltas da escola anterior, não é possível promover ou reter o aluno no ano letivo.

SOLUÇÃO:
- [ ] Criar funcionalidade para que seja possível copiar/transferir as informações de notas e faltas da escola origem para a escola destino, incluindo pareceres descritivos e conceitos, quando do processo de transferência de aluno para outra escolas da rede de ensino.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá,

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
