### ISSUE TITLE
Add Servers OpenAPI

### ISSUE THREAD

**Issue by msoares94** [portabilis/ieducar#885]
**CONTEXTO:**

Prezados, quando estiverem trabalhando na especificação do i-Educar nos padrões do OpenAPI, lembrar de adicionar um server diferente do endereço comercial do i-Educar.

```
"servers": [
    {
        "url": "https://ieducar.com.br",
        "description": "Endere\u00e7o do servidor da Aplica\u00e7\u00e3o"
    },
    {
        "url": "http://ieducar-community.dev.local",
        "description": "Endere\u00e7o do servidor da Aplica\u00e7\u00e3o"
    }
],
```
Dessa forma, será possível a Comunidade utilizar o endereço `http://ieducar-community.dev.local/docs-api#/` e testar utilizando o `Try it out` disponibilizado pelo próprio Swagger, sem a necessidade de criar os métodos no Postman ou outra ferramenta.

Não realizo um PR para esse caso pois não sei onde colocaria essa informação, tentei no arquivo public/openapi.json porém ele me parece ser regado automaticamente.

**Comment by edersoares** [comment]
@marcosoliveirasoares94 acredito que foi resolvido em https://github.com/portabilis/i-educar/commit/18ab2cc7afe2d697151d9494eb35fde461803370 e https://github.com/portabilis/i-educar/commit/2af638e383ae1af9d27ea6b6660589b30ed12c4b.
