### ISSUE TITLE
Criar funcionalidade para controle de dados de uniforme escolar, médico e socioeconômico (Educacenso/INEP)

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#89]
MENU:
i-Educar - Escola > Cadastro > Aluno > Alunos

PROBLEMA:
Faz-se necessária a adaptação do sistema para atender ao layout de dados do Educacenso/INEP, visando a exportação de dados automatizada. 

SOLUÇÃO:
Durante a análise das alterações, além de atender as informações de uniforme escolar, previstas em layouts anteriores do Educacenso, também foi planejado a inclusão de campos para o controle dos dados médicos e outros socioeconômicos de alunos.

- [x] Acrescentar opções para controlar se recebe ou não informe escolar e campos para itens como blusas, jaquetas, calças, meias, calçado e os tamanhos de cada item.
- [x] Acrescentar opções para controlar dados de saúde como peso; grupo sanguíneo, fator RH; carteira do SUS; se alérgico e quais tipos de alergia; se é fumante; se já contribuiu algum tipo de doença como sarampo, catapora, caxumba e outras; se está passando por algum tratamento; dados de plano de saúde; atividade física; medicação específica; informação de contato e telefones e quem avisar, nos casos de emergência, dentre outros;
- [x] Acrescentar opções para controlar informações de moradia, tais como: tipo de moradia, situação, número de quartos, salas, copas, banheiros, garagens; Se possui empregada doméstica, automóvel, motocicleta, computador, geladeira, fogão, máquina de lavar, microondas, televisão, telefone, celular, nr. de residentes, renda familiar; se possui água encada, poço, energia, esgoto, fossa e lixo.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá,

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.

**Comment by giustin** [comment]
Olá, @lucassch e @carolinesalib !

Para conhecimento, nesta issue também foram aplicadas as seguintes correções:

* Acentuação do label e valor padrões dos campos "Religiao" e "Beneficio", na aba Dados pessoais;
* Alteração para padronização do campo de "Código inep" para "Código INEP";
* Alteração para padronização do campo "Data nascimento" para "Data de nascimento";
