### ISSUE TITLE
Apresentação do menu Escola ao acessar o menu Endereçamento

### ISSUE THREAD

**Issue by msoares94** [portabilis/ieducar#890]
**MENU:**

Início -> Endereçamento

**DESCRIÇÃO:**

Realizando teste funcionais na versão 2.8, foi identificado que o menú `Endereçamento` está com erro.

Ao clicar no menu lateral `Endereçamento` os submemus carregados na barra superior não corresponde aos menus presenta na versão 2.7, trazendo no seu lugar os submenus do menu lateral `Escola`

![image](https://user-images.githubusercontent.com/12193221/210865838-8044b0d9-5580-47e4-ba8b-54e34cc17e03.png)

**Comment by edersoares** [comment]
@marcosoliveirasoares94 estamos construindo um novo frontend em Vue.js que será liberado na versão 2.8 do i-Educar, como não fechamos a release ainda não está disponível.

Se for necessário utilizar o cadastro de endereçamento é preciso fazer revert deste commit https://github.com/portabilis/i-educar/commit/3077926a46faf6637e9245b871f667976a4486f8.

**Comment by msoares94** [comment]
Entendido @edersoares, então é devido a essas mudanças todas que estão ocorrendo para contemplar a nova versão do i-Educar.
