### ISSUE TITLE
Class "clsPmieducarConfiguracoesGerais" not found

### ISSUE THREAD

**Issue by JoseLourenc0** [portabilis/ieducar#899]
**DESCRIÇÃO:**

Eu acabei de clonar o repositório na branch 2.8, tentei iniciar a aplicação utilizando o docker, e ao rodar o comando abaixo ele travou na parte das migrações
```
docker-compose exec php composer new-install
```
Segue print do ocorrido:
![image](https://user-images.githubusercontent.com/66333618/221957487-361b40c9-1660-4556-ad04-1be99878c065.png)

**AMBIENTE:**

- Plataforma utilizada: Docker
- Sistema operacional e versão: Windows 10.0.19044

**Comment by robertfsousa** [comment]
@JoseLourenc0 Fiz uma análise e classe está sendo carregada normalmente no projeto. Testei também uma nova instalação e deu tudo certo, conforme as imagens abaixo.
Poderia apagar a pasta e tentar novamente?

![image](https://user-images.githubusercontent.com/5428199/222407826-3de8353b-a2d9-4d86-aac1-78fa7b4bdc74.png)
![image](https://user-images.githubusercontent.com/5428199/222408082-0d9ff0b7-8100-432b-9900-2b9a3481fd90.png)

**Comment by JoseLourenc0** [comment]
Bom dia, testei fazer assim como disse, apaguei a pasta e removi os containers + imagens do projeto para rodar de novo e novamente deu o mesmo problema. Vou tentar rodar no linux pra ver se roda

**Comment by JoseLourenc0** [comment]
Beleza por algum motivo paranormal a instalação parece ter corrido normalmente no ubuntu 22, acredito que terei que usar aqui por hora, @robertfsousa você conseguiria, por favor, me informar uma forma de popular o banco de maneira rápida de forma a não precisar cadastrar as turmas, alunos, series, cursos, matriculas etc tudo na mão?

**Comment by robertfsousa** [comment]
> Beleza por algum motivo paranormal a instalação parece ter corrido normalmente no ubuntu 22, acredito que terei que usar aqui por hora, @robertfsousa você conseguiria, por favor, me informar uma forma de popular o banco de maneira rápida de forma a não precisar cadastrar as turmas, alunos, series, cursos, matriculas etc tudo na mão?

Bom dia, você poderia criar um **seed** do laravel e rodar.
https://laravel.com/docs/10.x/seeding

Porém exige bastante conhecimento do **banco** e das **regras**. Pois, cada tela de cadastro envolve diversas regras e que se não seguir pode ocorrer erros de inconsistências no banco. O recomendado sempre é cadastrar usando as telas;

**Comment by JoseLourenc0** [comment]
> > Beleza por algum motivo paranormal a instalação parece ter corrido normalmente no ubuntu 22, acredito que terei que usar aqui por hora, @robertfsousa você conseguiria, por favor, me informar uma forma de popular o banco de maneira rápida de forma a não precisar cadastrar as turmas, alunos, series, cursos, matriculas etc tudo na mão?
> 
> Bom dia, você poderia criar um **seed** do laravel e rodar. https://laravel.com/docs/10.x/seeding
> 
> Porém exige bastante conhecimento do **banco** e das **regras**. Pois, cada tela de cadastro envole diversas regras e que se não seguir pode ocorrer erros de inconsistências no banco. O recomendado sempre é cadastrar usando as telas;

Bom dia,
O problema é que não possuo muito conhecimento do banco, quiçá das regras. Será se não tem algum dump que posso usar? Algo usado talvez para demonstrações, homologação ou algo assim?

**Comment by JoseLourenc0** [comment]
Boa tarde, vejo que esse pedido já foi feito antes também na issue #226

**Comment by edersoares** [comment]
@JoseLourenc0 pode usar agora a partir da branch [2.8](https://github.com/portabilis/i-educar/tree/2.8) o comando:

```bash
php artisan db:seed --class=DemoSeeder
```

Estarei encerrando a issue por hora.

**Comment by Tibasa** [comment]
> **DESCRIÇÃO:**
> 
> Eu acabei de clonar o repositório na branch 2.8, tentei iniciar a aplicação utilizando o docker, e ao rodar o comando abaixo ele travou na parte das migrações
> 
> ```
> docker-compose exec php composer new-install
> ```
> 
> Segue print do ocorrido: ![image](https://user-images.githubusercontent.com/66333618/221957487-361b40c9-1660-4556-ad04-1be99878c065.png)
> 
> **AMBIENTE:**
> 
> * Plataforma utilizada: Docker
> * Sistema operacional e versão: Windows 10.0.19044

Também tive esse problema ao tentar rodar no Windows. 

Para resolver o problema, incluí a seguinte linha no classmap do arquivo "composer,json":

"ieducar/intranet/include/pmieducar/clsPmieducarConfiguracoesGerais.inc.php" 

Portanto, o classmap ficou dessa forma:

"classmap": [
      "ieducar/intranet/include",
      "ieducar/lib",
      "ieducar/modules/*/Model",
      "ieducar/modules/Avaliacao/Service",
      "ieducar/modules/Avaliacao/Views",
      "ieducar/modules/FormulaMedia/Validate",
      "ieducar/intranet/include/pmieducar/clsPmieducarConfiguracoesGerais.inc.php"
  ], 

Em seguida executei o comando "composer dump-autoload".

Após isso, o processo das migrações seguiu normalmente.
