### ISSUE TITLE
Corrigir para que a opção de responsável pelo aluno não seja alterada durante a edição do cadastro

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#90]
MENU:
i-Educar - Escola > Cadastro > Aluno > Alunos

PROBLEMA:
Ao editar um aluno, que quando cadastrado tivesse sido informado como responsável outra pessoa, se o pai do aluno tiver sido cadastrado no sistema durante esta edição, o sistema está alterando automaticamente a marcação do pai como responsável.

SOLUÇÃO:
- [ ] Alterar para que ao editar o aluno, o sistema não marque automaticamente a opção "Pai" como responsável, mesmo que ele estiver cadastrado no sistema.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá,

Esse problema foi corrigido no commit: https://github.com/portabilis/ieducar/commit/c745fcdd2cb40853931b5ba5eb537cfb28862622#diff-63bddbd02fe3275b1a616df0366c93d0R88
