### ISSUE TITLE
Dúvida sobre a modularização dos módulos Biblioteca e Transporte

### ISSUE THREAD

**Issue by msoares94** [portabilis/ieducar#900]
**CONTEXTO:**

Prezados, é notório que o i-educar antes contemplava o módulo de **transporte** e **biblioteca** nativamente e tais módulos foram externalizados dando origem aos repositórios **i-educar-library-package** e **i-educar-transport-package**, que por sua vez é uma grande evolução.

Tenho uma seguinte dúvida, como se daria esse desacoplamento em uma implantação no qual o i-educar continha esses modulos nativamente pensando em realizar uma limpeza de módulos no qual não são utilizados, a pergunta mais precisamente é:

  - Se colocar o pacote externo do módulo na instalação do i-educar atual e executar um roolback ele removeria as migrations da implantação atual?

  - Se rodar as migrations do pacote externo em cima de um i-educar no qual já continha o módulo nativo, os menus podem ficar duplicados?

**Comment by edersoares** [comment]
@marcosoliveirasoares94 a Portábilis vem trabalhando para evoluir o i-Educar cada vez mais, os módulos de transporte e biblioteca estão entrando em desuso por nossa parte e foram liberados como pacotes externos justamente para a comunidade não perdê-los. Nós não vamos mais dar manutenção nestes módulos no futuro.

> Se colocar o pacote externo do módulo na instalação do i-educar atual e executar um roolback ele removeria as migrations da implantação atual?

Em tese sim, não fiz o teste, mas o rollback você terá que especificar o diretório das migrations

```bash
php artisan migrate:rollback --path=packages/portabilis/i-educar-library-package/database/migrations
```

> Se rodar as migrations do pacote externo em cima de um i-educar no qual já continha o módulo nativo, os menus podem ficar duplicados?

Não irão ficar duplicados, pois as migrations são as mesmas (tem os mesmos nomes) e não rodarão duas vezes.

**Comment by msoares94** [comment]
@edersoares, obrigado pelo retorno, essas informações são de grande ajuda para a comunidade!

**Comment by msoares94** [comment]
@edersoares, para deixar registrado aqui, fiz o teste, saiu no log algo inesperado!

Evidência do pacote implantado no servidor:
![image](https://user-images.githubusercontent.com/12193221/222922020-bf1809f9-4f9c-4f7a-ace2-ad922149f28c.png)

Evidência do não reconhecimento das migrations para realização do roolback.
![image](https://user-images.githubusercontent.com/12193221/222922055-fa1baae2-972f-483c-a2ec-c55ced5ad77e.png)

Qual a recomendação nesse caso!

Ah e tem momentos que ocorre esse outro erro aqui:

![image](https://user-images.githubusercontent.com/12193221/222922392-d5e64cb9-843a-4546-bffd-a20ea0f53d3e.png)

Acredito que removeram o método por engano!

**Comment by edersoares** [comment]
@marcosoliveirasoares94 desculpe a demora.

Acredito que é necessário entender quais os passos você executou. Em uma instalação já existente do i-Educar, nada seria modificado, bastava clonar os repositórios conforme readme.

Se é uma nova instalação, basicamente o fluxo também é igual. Sempre tenha certeza de ter executado o comando `composer plug-and-play` e por via das dúvidas `composer plug-and-play:update` para forçar o update.

O último erro em questão deve ser por causa que você voltou a uma versão antiga do i-Educar que não tinha o método `resolve` no arquivo LegacyController.

Abraço!

**Comment by edersoares** [comment]
@marcosoliveirasoares94 a branch https://github.com/portabilis/i-educar/tree/2.8 está atualizada e com um tutorial de instalação novo, quando possível veja se isso atende e ficou claro. Por hora estarei encerando a issue.

**Comment by msoares94** [comment]
@edersoares, passando para dar um feedback!

Sim, agora o erro não persiste, o rollback das migrations foram executadas, porém, os menus ainda são apresentados na aplicação.

Por hora podemos deixar a issue fechada e tratarmos isso em momento futuro, pois ao meu ver, faz sentido em intalações já existentes que contém o Pacote de Relatórios e os módulos nativos de Biblioteca e Transporte permitir a execução do rollback e a aplicação não mais apresentar seus devidos menus, sendo factível o administrador caso deseje, implantar os pacotes de forma separada e assim voltar com os menus.
