### ISSUE TITLE
Habilitar todos os módulos do sistema para a funcionalidade de criar tipos (perfis) de usuário

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#91]
MENU:
i-Educar - Escola > Administrativo > Tipo de usuário

PROBLEMA:
Ao criar/editar um novo tipo de usuário, no menu Administrativo > Tipo de Usuário, existe uma tabela com os módulos mostrando as permissões que podem ser concedidas para o novo tipo de usuário. Atualmente, essa tabela não mostra todos os módulos do sistema, sendo obrigado a alterar individualmente as permissões e por cada usuário em DRH > Cadastro de funcionários, tornando o processo muito custoso.

SOLUÇÃO:
- [ ] Alterar o cadastro Tipo de usuário para que a tabela exiba todos os módulos de permissões (Agenda, DRH, Endereçamento, i-Educar - Escola, i-Educar - Biblioteca, Pessoa F/J e Principal, etc).

OBSERVAÇÕES:
Não se aplica

**Comment by lucassch** [comment]
Olá,

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
