### ISSUE TITLE
Alterar busca dinâmica das matrículas para que não traga alunos desativados

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#92]
MENU:
Não se aplica.

SOLUÇÃO:
 - [x] Em alguns casos de utilização como em formulários de relatórios por exemplo, é importante ter validação para que o resultado traga apenas alunos matriculados e ativos no sistema.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá,

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
