### ISSUE TITLE
Adicionar validação de formatos de horários nos campos do cadastro de turma para evitar erro

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#93]
MENU:
i-Educar - Escola > Cadastros > Turma > Cadastrar

PROBLEMA:
Ao tentar cadastrar uma turma e nos campos de horário de início, fim ou intervalo informar uma hora inválida (acima de 24 horas ou acima de 59 minutos, ex: 25:00 ou 14:61) exibe a mensagem de erro:

Notice: Trying to get property of non-object in /home/portabilis/app/i-educar_test/releases/20130828144453/ieducar/intranet/c...
Erro php
pg_query(): Query failed: ERROR: date/time field value out of range: "14:61"

SOLUÇÃO:
- [x] Adicionar validação nos campos citados para que não ocorra problema com tipos de dados não permitidos para o banco de dados.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
