### ISSUE TITLE
Corrigir validação de carga horária ao editar e salvar um servidor

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#94]
MENU:
i-Educar - Escola > Servidores > Cadastrar

PROBLEMA:
Ao editar um servidor e salvar, mesmo que não sejam alteradas as informações do mesmo, a seguinte mensagem é exibida: "Preencha o campo Carga Horária corretamente". O validação solicita que a carga horária total seja maior que as Horas Alocadas ao servidor, porém, mesmo que a Carga horária supra essa necessidade, a mensagem ainda é apresentada.

SOLUÇÃO:
- [x] Corrigir validação de carga horária ao editar e salvar um servidor para que exiba a mensagem de validação corretamente, de acordo com a situação.

OBSERVAÇÕES:
Não se aplica

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
