### ISSUE TITLE
Alterar recurso que retorna matrícula em formulários para recuperar sempre a última do ano vigente

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#95]
MENU:
Não se aplica

SOLUÇÃO:
 - [x] Em alguns casos de utilização como em formulários de relatórios por exemplo, adicionar validação no recurso ```simpleSearchMatricula``` para que retorne sempre a última matrícula do ano para cada aluno.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
