### ISSUE TITLE
Adicionar recurso para visualizar quanto o aluno precisa na nota de exame para ser promovido

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#96]
MENU:
i-Educar - Escola > Movimentação > Faltas/notas > Lançamento por Turma

PROBLEMA:
Atualmente, quando um aluno não atinge a média final exigida de acordo com a regra de avaliação, ele fica em Exame, sendo necessário digitar a nota de exame para que o sistema calcule e exiba se o aluno foi promovido ou não. O problema é que não se conhece quanto o aluno precisa obter antecipadamente, e isto é de extrema importância no final de cada ano letivo, para professores, coordenadores e até alunos.

SOLUÇÃO:
- [ ] Adicionar recurso, que permita visualizar na própria funcionalidade de lançamento de notas, quanto cada aluno precisa obter na nota de exame para ser promovido.

OBSERVAÇÕES:
Não se aplica.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
