### ISSUE TITLE
Criar função para calcular frequência geral do aluno para finalidades diversas

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#98]
MENU:
Não se aplica

PROBLEMA:
Atualmente, para calcular a frequência geral de um aluno é necessário ser realizado diversos cálculos via SQL.

SOLUÇÃO:
- [x] Criar uma função que execute este cálculo recebendo por parâmetro apenas a matrícula do aluno.

OBSERVAÇÕES:
Este recurso pode ser utilizado para o desenvolvimento de funcionalidades dinâmicas que precisem exibir esta informação na tela.

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
