### ISSUE TITLE
Criar relatório de atestado de frequência que exiba frequência no formulário para atender ao Bolsa Família

### ISSUE THREAD

**Issue by giustin** [portabilis/ieducar#99]
i-Educar - Escola > Documentos > Atestados > Atestado de Frequência

SOLUÇÃO:
- [x] Criar modelo de relatório de atestado de frequência que contenham as seguintes informações:
 * Cabeçalho padrão e título descrito "Atestado de Frequência";
 * Texto do corpo e justificado ou alinhado à esquerda: Atestamos para os devidos fins que, o(a) aluno(a) ````Nome do aluno````, filho(a) de ````Nome da mãe```` e de ````Nome do pai````, nascido(a) em ````dd/mm/yyyy````, natural de ````Nome da cidade````, está frequentando em ````ano letivo```` o(a) ````Nome do curso```` no período ````Descrição do turno````.
 * Local, data e espaço para assinatura;
- [x] Adicionar ao formulário de emissão pelo menos a seleção da Instituição, Escola e Matrícula;
- [x] Adicionar ao formulário de emissão deste relatório uma opção para visualizar, antes da emissão, qual é a frequência do aluno. Este recurso ajudará a emissão do documento para os casos de cumprimento de condicionalidades do Bolsa Família, onde o aluno deve estar com a frequência escolar em dia para receber o benefício, evitando então fornecer o atestado para alunos infrequentes.

Exemplo de como o recurso pode ser implementado no formulário:
![image](https://cloud.githubusercontent.com/assets/1082624/6550039/6c414b6c-c5fd-11e4-8838-4462ad1d59ad.png)

OBSERVAÇÕES:
Implementar este relatório após o desenvolvimento da tarefa https://github.com/portabilis/ieducar/issues/98

**Comment by lucassch** [comment]
Olá!

Alterações publicadas e já disponíveis no ambiente oficial da Comunidade.

Para visualizar a alteração, acesse o ambiente em http://pagina.softwarepublico.gov.br/ieducar/vitrine.
